/**
 * 수식 편집 모달에 표시할 함수 분류, 사용법, 설명을 정의한다.
 *
 * 함수 목록은 core의 `FORMULA_FUNCTIONS`와 일치해야 한다. core에 함수를 추가할 때
 * 각 언어의 도움말도 함께 추가한다.
 */

/** 함수 인자 하나의 도움말. */
export interface FormulaHelpArgument {
  /** UI 언어로 쓴 인자 이름. `signature`의 표기와 같다. */
  name: string;
  /** 인자가 무엇을 받는지에 대한 설명. */
  description: string;
  /** 생략할 수 있는 인자면 true. */
  optional?: boolean;
  /** 같은 종류의 인자를 여러 개 이어 쓸 수 있으면 true. */
  variadic?: boolean;
}

/** 함수 이름, 사용법, 설명과 인자·반환값으로 구성된 도움말 항목. */
export interface FormulaHelpEntry {
  name: string;
  /**
   * UI 언어로 작성한 사용법 표기. 예: `SUM(범위, …)`.
   *
   * @remarks
   * 표시용 문자열이다. 인자 목록은 이 문자열을 다시 해석하지 않고 `args`에서 읽는다.
   */
  signature: string;
  description: string;
  /** 인자 도움말 (사용법 표기와 같은 순서). 인자가 없으면 빈 배열. */
  args: FormulaHelpArgument[];
  /** 반환값 설명. */
  returns: string;
}

/** 함수 분류 한 묶음 */
export interface FormulaHelpCategory {
  title: string;
  functions: FormulaHelpEntry[];
}

const ko: FormulaHelpCategory[] = [
  {
    title: '집계',
    functions: [
      { name: 'SUM', signature: 'SUM(범위?, …)', description: '값·범위의 합계 (예: SUM($(items).$(amount)))',
        args: [{ name: '범위', description: '더할 값이나 목록 필드', variadic: true, optional: true }],
        returns: '합계 (수)',
      },
      { name: 'AVG', signature: 'AVG(범위, …)', description: '값·범위의 평균',
        args: [{ name: '범위', description: '평균을 낼 값이나 목록 필드', variadic: true }],
        returns: '평균 (수)',
      },
      { name: 'COUNT', signature: 'COUNT(범위?, …)', description: '빈 값을 뺀 항목 수',
        args: [{ name: '범위', description: '셀 값이나 목록 필드', variadic: true, optional: true }],
        returns: '빈 값을 뺀 개수 (수)',
      },
      { name: 'MIN', signature: 'MIN(범위?, …)', description: '가장 작은 값 (값이 없으면 0)',
        args: [{ name: '범위', description: '비교할 값이나 목록 필드', variadic: true, optional: true }],
        returns: '가장 작은 값 (수)',
      },
      { name: 'MAX', signature: 'MAX(범위?, …)', description: '가장 큰 값 (값이 없으면 0)',
        args: [{ name: '범위', description: '비교할 값이나 목록 필드', variadic: true, optional: true }],
        returns: '가장 큰 값 (수)',
      },
      { name: 'SUMIF', signature: 'SUMIF(범위, 조건, 합계범위?)', description: '조건에 맞는 값만 더한다 (조건 예: ">=1000")',
        args: [{ name: '범위', description: '조건을 검사할 값 목록' }, { name: '조건', description: '비교할 조건' }, { name: '합계범위', description: '실제로 더할 값 목록. 생략하면 범위를 더합니다', optional: true }],
        returns: '조건에 맞는 값의 합계 (수)',
      },
      { name: 'COUNTIF', signature: 'COUNTIF(범위, 조건)', description: '조건에 맞는 항목 수',
        args: [{ name: '범위', description: '조건을 검사할 값 목록' }, { name: '조건', description: '비교할 조건' }],
        returns: '조건에 맞는 개수 (수)',
      },
    ],
  },
  {
    title: '산술',
    functions: [
      { name: 'ROUND', signature: 'ROUND(수, 자릿수?)', description: '반올림 (자릿수 생략 시 정수로)',
        args: [{ name: '수', description: '반올림할 수' }, { name: '자릿수', description: '남길 소수 자릿수. 생략하면 정수', optional: true }],
        returns: '반올림한 수',
      },
      { name: 'FLOOR', signature: 'FLOOR(수, 자릿수?)', description: '내림',
        args: [{ name: '수', description: '내림할 수' }, { name: '자릿수', description: '남길 소수 자릿수. 생략하면 정수', optional: true }],
        returns: '내림한 수',
      },
      { name: 'CEIL', signature: 'CEIL(수, 자릿수?)', description: '올림',
        args: [{ name: '수', description: '올림할 수' }, { name: '자릿수', description: '남길 소수 자릿수. 생략하면 정수', optional: true }],
        returns: '올림한 수',
      },
      { name: 'ABS', signature: 'ABS(수)', description: '절댓값',
        args: [{ name: '수', description: '절댓값을 구할 수' }],
        returns: '부호를 없앤 수',
      },
    ],
  },
  {
    title: '문자열',
    functions: [
      { name: 'CONCAT', signature: 'CONCAT(값?, …)', description: '값들을 글자로 이어 붙인다',
        args: [{ name: '값', description: '이어 붙일 값', variadic: true, optional: true }],
        returns: '이어 붙인 글',
      },
      { name: 'LEFT', signature: 'LEFT(문자열, 글자 수?)', description: '왼쪽부터 지정한 글자 수만큼',
        args: [{ name: '문자열', description: '자를 글' }, { name: '글자 수', description: '왼쪽에서 가져올 글자 수. 생략하면 1', optional: true }],
        returns: '왼쪽에서 잘라낸 글',
      },
      { name: 'RIGHT', signature: 'RIGHT(문자열, 글자 수?)', description: '오른쪽부터 지정한 글자 수만큼',
        args: [{ name: '문자열', description: '자를 글' }, { name: '글자 수', description: '오른쪽에서 가져올 글자 수. 생략하면 1', optional: true }],
        returns: '오른쪽에서 잘라낸 글',
      },
      { name: 'MID', signature: 'MID(문자열, 시작, 길이)', description: '시작 위치(1부터)에서 지정 길이만큼',
        args: [{ name: '문자열', description: '자를 글' }, { name: '시작', description: '가져오기 시작할 위치 (1부터)' }, { name: '길이', description: '가져올 글자 수' }],
        returns: '잘라낸 글',
      },
      { name: 'REPLACE', signature: 'REPLACE(문자열, 찾기, 바꾸기)', description: '일치하는 부분을 모두 바꾼다',
        args: [{ name: '문자열', description: '바꿀 대상 글' }, { name: '찾기', description: '찾을 글' }, { name: '바꾸기', description: '대신 넣을 글' }],
        returns: '바꾼 글',
      },
      { name: 'TRIM', signature: 'TRIM(문자열)', description: '양끝 공백 제거',
        args: [{ name: '문자열', description: '공백을 지울 글' }],
        returns: '양끝 공백을 지운 글',
      },
      { name: 'UPPER', signature: 'UPPER(문자열)', description: '영문 대문자로',
        args: [{ name: '문자열', description: '바꿀 글' }],
        returns: '영문을 대문자로 바꾼 글',
      },
      { name: 'LOWER', signature: 'LOWER(문자열)', description: '영문 소문자로',
        args: [{ name: '문자열', description: '바꿀 글' }],
        returns: '영문을 소문자로 바꾼 글',
      },
    ],
  },
  {
    title: '조건',
    functions: [
      { name: 'IF', signature: 'IF(조건, 참일 때, 거짓일 때?)', description: '조건에 따라 두 값 중 하나',
        args: [{ name: '조건', description: '참·거짓을 내는 식' }, { name: '참일 때', description: '조건이 참일 때 쓸 값' }, { name: '거짓일 때', description: '조건이 거짓일 때 쓸 값. 생략하면 빈 값', optional: true }],
        returns: '조건에 따라 고른 값',
      },
      { name: 'AND', signature: 'AND(조건, …)', description: '전부 참이면 참',
        args: [{ name: '조건', description: '참·거짓을 내는 식', variadic: true }],
        returns: '전부 참이면 참 (논리값)',
      },
      { name: 'OR', signature: 'OR(조건, …)', description: '하나라도 참이면 참',
        args: [{ name: '조건', description: '참·거짓을 내는 식', variadic: true }],
        returns: '하나라도 참이면 참 (논리값)',
      },
    ],
  },
  {
    title: '포맷',
    functions: [
      { name: 'FORMAT_NUMBER', signature: 'FORMAT_NUMBER(수, 소수 자릿수?)', description: '1,234,567처럼 자릿수 구분 표기',
        args: [{ name: '수', description: '표기할 수' }, { name: '소수 자릿수', description: '표시할 소수 자릿수. 생략하면 입력값의 소수 부분을 유지합니다', optional: true }],
        returns: '자릿수를 구분한 글',
      },
      { name: 'FORMAT_DATE', signature: 'FORMAT_DATE(날짜, 패턴?)', description: '날짜 표기 (기본 YYYY-MM-DD)',
        args: [{ name: '날짜', description: '표기할 날짜' }, { name: '패턴', description: '표기 형식. 생략하면 YYYY-MM-DD', optional: true }],
        returns: '형식에 맞춘 날짜 글',
      },
      { name: 'NUMBER_TO_KOREAN', signature: 'NUMBER_TO_KOREAN(수)', description: '금액을 한글로 (예: 일만이천삼백)',
        args: [{ name: '수', description: '한글로 옮길 금액' }],
        returns: '한글로 옮긴 금액 글',
      },
    ],
  },
  {
    title: '날짜',
    functions: [
      { name: 'TODAY', signature: 'TODAY()', description: '오늘 날짜 (YYYY-MM-DD)',
        args: [],
        returns: '오늘 날짜 (YYYY-MM-DD)',
      },
      { name: 'DATE_ADD', signature: 'DATE_ADD(날짜, 증감량, 단위?)', description: '날짜 더하기·빼기 (단위: days·months·years)',
        args: [{ name: '날짜', description: '기준 날짜' }, { name: '증감량', description: '더할 양. 음수면 뺍니다' }, { name: '단위', description: 'days·months·years 중 하나. 생략하면 days', optional: true }],
        returns: '옮긴 날짜 (YYYY-MM-DD)',
      },
      { name: 'DATE_DIFF', signature: 'DATE_DIFF(시작, 끝, 단위?)', description: '두 날짜의 차이 (끝 − 시작)',
        args: [{ name: '시작', description: '시작 날짜' }, { name: '끝', description: '끝 날짜' }, { name: '단위', description: 'days·months·years 중 하나. 생략하면 days', optional: true }],
        returns: '끝에서 시작을 뺀 차이 (수)',
      },
    ],
  },
  {
    title: '세무',
    functions: [
      { name: 'VAT', signature: 'VAT(공급가액, 세율?)', description: '부가세액 (기본 세율 10%)',
        args: [{ name: '공급가액', description: '세액을 구할 금액' }, { name: '세율', description: '백분율로 적은 세율. 생략하면 10 (10%)', optional: true }],
        returns: '부가세액 (수)',
      },
    ],
  },
  {
    title: '타입 변환',
    functions: [
      { name: 'TO_NUMBER', signature: 'TO_NUMBER(값)', description: '글자를 수로 (빈 값은 0). 숫자 자리에 글자를 넣을 때',
        args: [{ name: '값', description: '수로 바꿀 값' }],
        returns: '바꾼 수 (빈 값은 0)',
      },
      { name: 'TO_STRING', signature: 'TO_STRING(값)', description: '수·논리를 글자로',
        args: [{ name: '값', description: '글로 바꿀 값' }],
        returns: '바꾼 글',
      },
      { name: 'TO_DATE', signature: 'TO_DATE(값)', description: '날짜 문자열을 검증해 YYYY-MM-DD로',
        args: [{ name: '값', description: '검증할 날짜 글' }],
        returns: 'YYYY-MM-DD 형식의 날짜',
      },
    ],
  },
];

const en: FormulaHelpCategory[] = [
  {
    title: 'Aggregation',
    functions: [
      { name: 'SUM', signature: 'SUM(range?, …)', description: 'Sum of values/ranges (e.g. SUM($(items).$(amount)))',
        args: [{ name: 'range', description: 'Values or list fields to add', variadic: true, optional: true }],
        returns: 'The sum (number)',
      },
      { name: 'AVG', signature: 'AVG(range, …)', description: 'Average of values/ranges',
        args: [{ name: 'range', description: 'Values or list fields to average', variadic: true }],
        returns: 'The average (number)',
      },
      { name: 'COUNT', signature: 'COUNT(range?, …)', description: 'Number of non-empty items',
        args: [{ name: 'range', description: 'Values or list fields to count', variadic: true, optional: true }],
        returns: 'Count excluding empty values (number)',
      },
      { name: 'MIN', signature: 'MIN(range?, …)', description: 'Smallest value (0 when empty)',
        args: [{ name: 'range', description: 'Values or list fields to compare', variadic: true, optional: true }],
        returns: 'The smallest value (number)',
      },
      { name: 'MAX', signature: 'MAX(range?, …)', description: 'Largest value (0 when empty)',
        args: [{ name: 'range', description: 'Values or list fields to compare', variadic: true, optional: true }],
        returns: 'The largest value (number)',
      },
      { name: 'SUMIF', signature: 'SUMIF(range, criteria, sumRange?)', description: 'Sum only matching values (e.g. ">=1000")',
        args: [{ name: 'range', description: 'Values to test against the criteria' }, { name: 'criteria', description: 'The comparison to apply' }, { name: 'sumRange', description: 'Values to add instead. Defaults to range', optional: true }],
        returns: 'Sum of matching values (number)',
      },
      { name: 'COUNTIF', signature: 'COUNTIF(range, criteria)', description: 'Count matching items',
        args: [{ name: 'range', description: 'Values to test against the criteria' }, { name: 'criteria', description: 'The comparison to apply' }],
        returns: 'Count of matching values (number)',
      },
    ],
  },
  {
    title: 'Math',
    functions: [
      { name: 'ROUND', signature: 'ROUND(number, digits?)', description: 'Round (to integer when digits omitted)',
        args: [{ name: 'number', description: 'The number to round' }, { name: 'digits', description: 'Decimal places to keep. Defaults to integer', optional: true }],
        returns: 'The rounded number',
      },
      { name: 'FLOOR', signature: 'FLOOR(number, digits?)', description: 'Round down',
        args: [{ name: 'number', description: 'The number to round down' }, { name: 'digits', description: 'Decimal places to keep. Defaults to integer', optional: true }],
        returns: 'The rounded-down number',
      },
      { name: 'CEIL', signature: 'CEIL(number, digits?)', description: 'Round up',
        args: [{ name: 'number', description: 'The number to round up' }, { name: 'digits', description: 'Decimal places to keep. Defaults to integer', optional: true }],
        returns: 'The rounded-up number',
      },
      { name: 'ABS', signature: 'ABS(number)', description: 'Absolute value',
        args: [{ name: 'number', description: 'The number to take the absolute value of' }],
        returns: 'The number without its sign',
      },
    ],
  },
  {
    title: 'Text',
    functions: [
      { name: 'CONCAT', signature: 'CONCAT(value?, …)', description: 'Join values as text',
        args: [{ name: 'value', description: 'Values to join', variadic: true, optional: true }],
        returns: 'The joined text',
      },
      { name: 'LEFT', signature: 'LEFT(text, count?)', description: 'Leftmost characters',
        args: [{ name: 'text', description: 'The text to cut' }, { name: 'count', description: 'Characters to take from the left. Defaults to 1', optional: true }],
        returns: 'The leftmost characters',
      },
      { name: 'RIGHT', signature: 'RIGHT(text, count?)', description: 'Rightmost characters',
        args: [{ name: 'text', description: 'The text to cut' }, { name: 'count', description: 'Characters to take from the right. Defaults to 1', optional: true }],
        returns: 'The rightmost characters',
      },
      { name: 'MID', signature: 'MID(text, start, length)', description: 'Substring from start (1-based)',
        args: [{ name: 'text', description: 'The text to cut' }, { name: 'start', description: 'Where to start, 1-based' }, { name: 'length', description: 'How many characters to take' }],
        returns: 'The extracted text',
      },
      { name: 'REPLACE', signature: 'REPLACE(text, search, replacement)', description: 'Replace every match',
        args: [{ name: 'text', description: 'The text to search in' }, { name: 'search', description: 'The text to find' }, { name: 'replacement', description: 'The text to put instead' }],
        returns: 'The replaced text',
      },
      { name: 'TRIM', signature: 'TRIM(text)', description: 'Strip surrounding whitespace',
        args: [{ name: 'text', description: 'The text to strip' }],
        returns: 'The text without surrounding whitespace',
      },
      { name: 'UPPER', signature: 'UPPER(text)', description: 'To upper case',
        args: [{ name: 'text', description: 'The text to convert' }],
        returns: 'The text in upper case',
      },
      { name: 'LOWER', signature: 'LOWER(text)', description: 'To lower case',
        args: [{ name: 'text', description: 'The text to convert' }],
        returns: 'The text in lower case',
      },
    ],
  },
  {
    title: 'Logic',
    functions: [
      { name: 'IF', signature: 'IF(condition, then, else?)', description: 'One of two values by condition',
        args: [{ name: 'condition', description: 'An expression that yields TRUE or FALSE' }, { name: 'then', description: 'The value to use when true' }, { name: 'else', description: 'The value to use when false. Empty when omitted', optional: true }],
        returns: 'The value chosen by the condition',
      },
      { name: 'AND', signature: 'AND(condition, …)', description: 'True when all are true',
        args: [{ name: 'condition', description: 'Expressions that yield TRUE or FALSE', variadic: true }],
        returns: 'TRUE when every condition is true',
      },
      { name: 'OR', signature: 'OR(condition, …)', description: 'True when any is true',
        args: [{ name: 'condition', description: 'Expressions that yield TRUE or FALSE', variadic: true }],
        returns: 'TRUE when any condition is true',
      },
    ],
  },
  {
    title: 'Format',
    functions: [
      { name: 'FORMAT_NUMBER', signature: 'FORMAT_NUMBER(number, digits?)', description: 'Grouped digits like 1,234,567',
        args: [{ name: 'number', description: 'The number to format' }, { name: 'digits', description: "Decimal places to show. Without it the number's own decimals are kept", optional: true }],
        returns: 'The grouped number as text',
      },
      { name: 'FORMAT_DATE', signature: 'FORMAT_DATE(date, pattern?)', description: 'Format a date (default YYYY-MM-DD)',
        args: [{ name: 'date', description: 'The date to format' }, { name: 'pattern', description: 'The format. Defaults to YYYY-MM-DD', optional: true }],
        returns: 'The formatted date as text',
      },
      { name: 'NUMBER_TO_KOREAN', signature: 'NUMBER_TO_KOREAN(number)', description: 'Amount in Korean words',
        args: [{ name: 'number', description: 'The amount to spell out' }],
        returns: 'The amount in Korean words',
      },
    ],
  },
  {
    title: 'Date',
    functions: [
      { name: 'TODAY', signature: 'TODAY()', description: 'Today (YYYY-MM-DD)',
        args: [],
        returns: 'Today\'s date (YYYY-MM-DD)',
      },
      { name: 'DATE_ADD', signature: 'DATE_ADD(date, amount, unit?)', description: 'Shift a date (unit: days·months·years)',
        args: [{ name: 'date', description: 'The starting date' }, { name: 'amount', description: 'How much to add. Negative subtracts' }, { name: 'unit', description: 'One of days, months, years. Defaults to days', optional: true }],
        returns: 'The shifted date (YYYY-MM-DD)',
      },
      { name: 'DATE_DIFF', signature: 'DATE_DIFF(start, end, unit?)', description: 'Difference between dates (end − start)',
        args: [{ name: 'start', description: 'The start date' }, { name: 'end', description: 'The end date' }, { name: 'unit', description: 'One of days, months, years. Defaults to days', optional: true }],
        returns: 'End minus start (number)',
      },
    ],
  },
  {
    title: 'Tax',
    functions: [
      { name: 'VAT', signature: 'VAT(amount, rate?)', description: 'VAT amount (default rate 10%)',
        args: [{ name: 'amount', description: 'The amount to tax' }, { name: 'rate', description: 'The rate in percent. Defaults to 10 (10%)', optional: true }],
        returns: 'The VAT amount (number)',
      },
    ],
  },
  {
    title: 'Type conversion',
    functions: [
      { name: 'TO_NUMBER', signature: 'TO_NUMBER(value)', description: 'Text to number (empty is 0). Use where a number is required',
        args: [{ name: 'value', description: 'The value to convert' }],
        returns: 'The converted number (empty becomes 0)',
      },
      { name: 'TO_STRING', signature: 'TO_STRING(value)', description: 'Number/boolean to text',
        args: [{ name: 'value', description: 'The value to convert' }],
        returns: 'The converted text',
      },
      { name: 'TO_DATE', signature: 'TO_DATE(value)', description: 'Validate a date string to YYYY-MM-DD',
        args: [{ name: 'value', description: 'The date text to validate' }],
        returns: 'The date as YYYY-MM-DD',
      },
    ],
  },
];

const ja: FormulaHelpCategory[] = [
  {
    title: '集計',
    functions: [
      { name: 'SUM', signature: 'SUM(範囲?, …)', description: '値・範囲の合計 (例: SUM($(items).$(amount)))',
        args: [{ name: '範囲', description: '合計する値または一覧フィールド', variadic: true, optional: true }],
        returns: '合計 (数値)',
      },
      { name: 'AVG', signature: 'AVG(範囲, …)', description: '値・範囲の平均',
        args: [{ name: '範囲', description: '平均を求める値または一覧フィールド', variadic: true }],
        returns: '平均 (数値)',
      },
      { name: 'COUNT', signature: 'COUNT(範囲?, …)', description: '空の値を除いた項目数',
        args: [{ name: '範囲', description: '数える値または一覧フィールド', variadic: true, optional: true }],
        returns: '空の値を除いた個数 (数値)',
      },
      { name: 'MIN', signature: 'MIN(範囲?, …)', description: '最小値 (値がなければ0)',
        args: [{ name: '範囲', description: '比較する値または一覧フィールド', variadic: true, optional: true }],
        returns: '最小値 (数値)',
      },
      { name: 'MAX', signature: 'MAX(範囲?, …)', description: '最大値 (値がなければ0)',
        args: [{ name: '範囲', description: '比較する値または一覧フィールド', variadic: true, optional: true }],
        returns: '最大値 (数値)',
      },
      { name: 'SUMIF', signature: 'SUMIF(範囲, 条件, 合計範囲?)', description: '条件に合う値だけを合計する (条件の例: ">=1000")',
        args: [{ name: '範囲', description: '条件を判定する値の一覧' }, { name: '条件', description: '適用する比較条件' }, { name: '合計範囲', description: '実際に合計する値の一覧。省略すると範囲を合計します', optional: true }],
        returns: '条件に合う値の合計 (数値)',
      },
      { name: 'COUNTIF', signature: 'COUNTIF(範囲, 条件)', description: '条件に合う項目数',
        args: [{ name: '範囲', description: '条件を判定する値の一覧' }, { name: '条件', description: '適用する比較条件' }],
        returns: '条件に合う個数 (数値)',
      },
    ],
  },
  {
    title: '算術',
    functions: [
      { name: 'ROUND', signature: 'ROUND(数値, 桁数?)', description: '四捨五入 (桁数を省略すると整数に)',
        args: [{ name: '数値', description: '四捨五入する数値' }, { name: '桁数', description: '残す小数桁数。省略すると整数', optional: true }],
        returns: '四捨五入した数値',
      },
      { name: 'FLOOR', signature: 'FLOOR(数値, 桁数?)', description: '切り捨て',
        args: [{ name: '数値', description: '切り捨てる数値' }, { name: '桁数', description: '残す小数桁数。省略すると整数', optional: true }],
        returns: '切り捨てた数値',
      },
      { name: 'CEIL', signature: 'CEIL(数値, 桁数?)', description: '切り上げ',
        args: [{ name: '数値', description: '切り上げる数値' }, { name: '桁数', description: '残す小数桁数。省略すると整数', optional: true }],
        returns: '切り上げた数値',
      },
      { name: 'ABS', signature: 'ABS(数値)', description: '絶対値',
        args: [{ name: '数値', description: '絶対値を求める数値' }],
        returns: '符号を外した数値',
      },
    ],
  },
  {
    title: '文字列',
    functions: [
      { name: 'CONCAT', signature: 'CONCAT(値?, …)', description: '複数の値を文字列として連結する',
        args: [{ name: '値', description: '連結する値', variadic: true, optional: true }],
        returns: '連結した文字列',
      },
      { name: 'LEFT', signature: 'LEFT(文字列, 文字数?)', description: '左から指定した文字数だけ',
        args: [{ name: '文字列', description: '切り出す文字列' }, { name: '文字数', description: '左から取る文字数。省略すると1', optional: true }],
        returns: '左から切り出した文字列',
      },
      { name: 'RIGHT', signature: 'RIGHT(文字列, 文字数?)', description: '右から指定した文字数だけ',
        args: [{ name: '文字列', description: '切り出す文字列' }, { name: '文字数', description: '右から取る文字数。省略すると1', optional: true }],
        returns: '右から切り出した文字列',
      },
      { name: 'MID', signature: 'MID(文字列, 開始, 長さ)', description: '開始位置(1から)から指定した長さだけ',
        args: [{ name: '文字列', description: '切り出す文字列' }, { name: '開始', description: '取り出しを始める位置 (1から)' }, { name: '長さ', description: '取り出す文字数' }],
        returns: '切り出した文字列',
      },
      { name: 'REPLACE', signature: 'REPLACE(文字列, 検索, 置換)', description: '一致する部分をすべて置き換える',
        args: [{ name: '文字列', description: '置き換える対象の文字列' }, { name: '検索', description: '探す文字列' }, { name: '置換', description: '代わりに入れる文字列' }],
        returns: '置き換えた文字列',
      },
      { name: 'TRIM', signature: 'TRIM(文字列)', description: '前後の空白を除去',
        args: [{ name: '文字列', description: '空白を除去する文字列' }],
        returns: '前後の空白を除いた文字列',
      },
      { name: 'UPPER', signature: 'UPPER(文字列)', description: '英字を大文字に',
        args: [{ name: '文字列', description: '変換する文字列' }],
        returns: '英字を大文字にした文字列',
      },
      { name: 'LOWER', signature: 'LOWER(文字列)', description: '英字を小文字に',
        args: [{ name: '文字列', description: '変換する文字列' }],
        returns: '英字を小文字にした文字列',
      },
    ],
  },
  {
    title: '条件',
    functions: [
      { name: 'IF', signature: 'IF(条件, 真のとき, 偽のとき?)', description: '条件に応じて2つの値のいずれか',
        args: [{ name: '条件', description: '真偽を返す式' }, { name: '真のとき', description: '条件が真のときに使う値' }, { name: '偽のとき', description: '条件が偽のときに使う値。省略すると空', optional: true }],
        returns: '条件に応じて選ばれた値',
      },
      { name: 'AND', signature: 'AND(条件, …)', description: 'すべて真なら真',
        args: [{ name: '条件', description: '真偽を返す式', variadic: true }],
        returns: 'すべて真なら真 (論理値)',
      },
      { name: 'OR', signature: 'OR(条件, …)', description: 'いずれかが真なら真',
        args: [{ name: '条件', description: '真偽を返す式', variadic: true }],
        returns: 'いずれかが真なら真 (論理値)',
      },
    ],
  },
  {
    title: '書式',
    functions: [
      { name: 'FORMAT_NUMBER', signature: 'FORMAT_NUMBER(数値, 小数桁数?)', description: '1,234,567のように桁区切り表記',
        args: [{ name: '数値', description: '表記する数値' }, { name: '小数桁数', description: '表示する小数桁数。省略すると元の小数をそのまま表記', optional: true }],
        returns: '桁区切りした文字列',
      },
      { name: 'FORMAT_DATE', signature: 'FORMAT_DATE(日付, パターン?)', description: '日付の表記 (既定 YYYY-MM-DD)',
        args: [{ name: '日付', description: '表記する日付' }, { name: 'パターン', description: '表記形式。省略すると YYYY-MM-DD', optional: true }],
        returns: '書式を適用した日付文字列',
      },
      { name: 'NUMBER_TO_KOREAN', signature: 'NUMBER_TO_KOREAN(数値)', description: '金額を韓国語表記に (例: 일만이천삼백)',
        args: [{ name: '数値', description: '韓国語表記にする金額' }],
        returns: '韓国語表記にした金額文字列',
      },
    ],
  },
  {
    title: '日付',
    functions: [
      { name: 'TODAY', signature: 'TODAY()', description: '今日の日付 (YYYY-MM-DD)',
        args: [],
        returns: '今日の日付 (YYYY-MM-DD)',
      },
      { name: 'DATE_ADD', signature: 'DATE_ADD(日付, 増減量, 単位?)', description: '日付の加算・減算 (単位: days・months・years)',
        args: [{ name: '日付', description: '基準となる日付' }, { name: '増減量', description: '加える量。負の数なら引きます' }, { name: '単位', description: 'days・months・years のいずれか。省略すると days', optional: true }],
        returns: '移動した日付 (YYYY-MM-DD)',
      },
      { name: 'DATE_DIFF', signature: 'DATE_DIFF(開始, 終了, 単位?)', description: '2つの日付の差 (終了 − 開始)',
        args: [{ name: '開始', description: '開始日' }, { name: '終了', description: '終了日' }, { name: '単位', description: 'days・months・years のいずれか。省略すると days', optional: true }],
        returns: '終了から開始を引いた差 (数値)',
      },
    ],
  },
  {
    title: '税務',
    functions: [
      { name: 'VAT', signature: 'VAT(課税標準額, 税率?)', description: '消費税額 (既定の税率10%)',
        args: [{ name: '課税標準額', description: '税額を求める金額' }, { name: '税率', description: '百分率で表した税率。省略すると 10 (10%)', optional: true }],
        returns: '消費税額 (数値)',
      },
    ],
  },
  {
    title: '型変換',
    functions: [
      { name: 'TO_NUMBER', signature: 'TO_NUMBER(値)', description: '文字を数値に (空は0)。数値が必要な場所で使う',
        args: [{ name: '値', description: '数値に変換する値' }],
        returns: '変換した数値 (空は0)',
      },
      { name: 'TO_STRING', signature: 'TO_STRING(値)', description: '数値・論理値を文字に',
        args: [{ name: '値', description: '文字に変換する値' }],
        returns: '変換した文字列',
      },
      { name: 'TO_DATE', signature: 'TO_DATE(値)', description: '日付文字列を検証して YYYY-MM-DD に',
        args: [{ name: '値', description: '検証する日付文字列' }],
        returns: 'YYYY-MM-DD 形式の日付',
      },
    ],
  },
];

const HELP = { ko, en, ja } as const;

/**
 * 로케일에 맞는 함수 도움말을 반환한다. 지역 코드는 제외하고 언어 코드만 사용한다.
 * 지원하지 않는 언어에는 영어 도움말을 반환한다.
 *
 * @param locale - UI 언어 (생략하면 영어)
 * @returns 분류별 함수 도움말 목록
 */
export function getFormulaHelp(locale?: string): FormulaHelpCategory[] {
  const language = locale?.toLowerCase().split('-')[0];
  return language && language in HELP ? HELP[language as keyof typeof HELP] : HELP.en;
}
