/**
 * UI 문구 리소스.
 *
 * 문구는 이 파일의 언어별 사전에 정의하고 컴포넌트는 `locale` 속성으로 사전을 선택합니다.
 * 새 문구는 모든 언어 사전에 추가하며 `SlipStrings` 타입으로 키 구성을 검사합니다.
 */

/** 지원하는 UI 언어. */
export type SlipLocale = 'ko' | 'en' | 'ja';

const ko = {
  viewer: {
    noFile: '표시할 .slip 파일이 없습니다.',
    loading: 'PDF를 생성하고 있습니다…',
    parseError: '.slip 파일을 읽을 수 없습니다.',
    renderError: 'PDF 렌더링에 실패했습니다.',
    pdfTitle: 'PDF 미리보기',
  },
  designer: {
    noTemplate: '양식을 불러오세요.',
    parseError: '.slip 파일을 읽을 수 없습니다.',
    onlyTemplate: '디자이너는 양식(template) 파일만 편집할 수 있습니다.',
    addText: '텍스트',
    addGrid: '그리드',
    addImage: '이미지',
    addField: '필드',
    addBarcode: '바코드',
    delete: '삭제',
    copy: '복사',
    paste: '붙여넣기',
    undo: '되돌리기',
    redo: '다시 실행',
    preview: '미리보기',
    edit: '편집',
    preset: '프리셋',
    presetTradeStatement: '거래명세서',
    presetInvoice: '청구서',
    addPage: '페이지 추가',
    deletePage: '페이지 삭제',
    showBadges: '요소 확인',
    grid: '격자',
    gridNone: '격자 없음',
    gridGap: '격자 간격',
    gridColor: '격자 색',
    colorGray: '회색',
    colorBlue: '파랑',
    colorRed: '빨강',
    colorGreen: '초록',
    pageMoveForward: '페이지 앞으로',
    pageMoveBackward: '페이지 뒤로',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
    sidebarPages: '페이지',
    pageLabel: '{n}페이지',
    pageSettings: '페이지 설정',
    pageName: '이름',
    pageKey: '물리명',
    pageNumberShow: '번호 표시',
    pageNumberPosition: '번호 위치',
    pagePosBottomLeft: '아래 왼쪽',
    pagePosBottomCenter: '아래 가운데',
    pagePosBottomRight: '아래 오른쪽',
    pagePosTopLeft: '위 왼쪽',
    pagePosTopCenter: '위 가운데',
    pagePosTopRight: '위 오른쪽',
    pageOrder: '페이지 순서',
    sidebarElements: '요소',
    sidebarParameters: '파라미터',
    typeBarcode: '바코드',
    /* 바코드 요소 편집  */
    barcodeKind: '바코드 종류',
    barcodeValue: '바코드 값',
    barcodeWarnDigits: '{name}은 숫자 {n}자리여야 합니다',
    barcodeWarnCode39: 'CODE39는 대문자·숫자·일부 기호(- . $ / + % 공백)만 됩니다',
    expandRow: '펼치기',
    collapseRow: '접기',
    /* 요소 목록에서 그리드를 펼쳤을 때 값·수식 셀 줄  */
    gridCellAt: '{r}행 {c}열',
    /* 요소 그룹화  */
    groupSelection: '여러 요소',
    selectedCount: '선택 수',
    groupElements: '그룹으로 묶기',
    ungroupElements: '그룹 해제',
    panelBasic: '기본',
    panelLayout: '배치',
    panelStructure: '구조',
    panelValue: '값',
    panelPaper: '용지',
    panelPageNumber: '페이지 번호',
    formSettings: '양식 설정',
    formTitle: '제목',
    paperSize: '용지 크기',
    paperCustom: '직접 입력',
    /* 용지 공급·저장  */
    paperSaveThis: '이 크기 저장',
    paperSizeName: '용지 이름',
    orientation: '방향',
    portrait: '세로',
    landscape: '가로',
    margin: '여백',
    marginTop: '위',
    marginRight: '오른쪽',
    marginBottom: '아래',
    marginLeft: '왼쪽',
    name: '이름',
    anchor: '기준점',
    anchorTL: '좌상',
    anchorT: '상',
    anchorTR: '우상',
    anchorL: '좌',
    anchorC: '중앙',
    anchorR: '우',
    anchorBL: '좌하',
    anchorB: '하',
    anchorBR: '우하',
    width: '너비',
    height: '높이',
    content: '내용',
    parameter: '파라미터',
    formula: '수식',
    fontName: '폰트',
    fontDefault: '기본 폰트',
    fontSize: '글자 크기',
    alignment: '정렬',
    rows: '행',
    columns: '열',
    cell: '선택 셀',
    gridBack: '그리드 설정',
    /** 그리드  */
    rowHeight: '행 높이',
    columnWidth: '열 너비',
    overflow: '긴 내용 표시',
    overflowInherit: '그리드 설정 사용',
    overflowClip: '넘친 부분 숨김',
    overflowShrink: '글자 크기 줄임',
    repeatSection: '반복',
    repeatOn: '사용',
    repeatMaxItems: '최대 항목 수',
    repeatMaxItemsNone: '상한 없음',
    advancedSettings: '고급 설정',
    selectRole: '표시 방식 선택',
    repeatCellHint: '반복',
    paginationMode: '페이지 방식',
    paginationAuto: '자동 확장',
    paginationFixed: '고정 페이지',
    minItems: '최소 표시 항목 수',
    itemsPerPage: '페이지당 항목 수',
    groupBy: '그룹 기준',
    groupByNone: '사용 안 함',
    bandSection: '행 구간',
    gridCommandSection: '빠른 구성',
    gridCommandManual: '직접 편집',
    gridCommandHeaderName: '헤더',
    gridCommandGroupSubtotalName: '그룹 소계',
    gridCommandPageSubtotalName: '페이지 소계',
    gridCommandFinalTotalName: '최종 합계',
    gridCommandPreview: '추가 결과',
    gridCommandField: '합산할 필드',
    gridCommandFieldMissing: '숫자 필드 없음',
    gridCommandLocation: '위치',
    gridCommandDisplay: '표시',
    gridCommandCalculation: '계산',
    gridCommandNone: '없음',
    gridCommandEachGroup: '각 그룹',
    gridCommandOnce: '한 번',
    gridCommandGroupCalculation: '{field}의 그룹 합계',
    gridCommandPageCalculation: '{field}의 페이지 합계',
    gridCommandFinalCalculation: '{field}의 전체 합계',
    gridCommandApply: '이 행 추가',
    gridCommandGroupRequired: '고급 설정에서 그룹 기준을 먼저 고르세요.',
    gridCommandNumberRequired: '목록 파라미터에 숫자 필드를 추가하세요.',
    bandRole: '표시 방식',
    bandFromRow: '시작 행',
    bandToRow: '종료 행',
    bandItem: '데이터 반복 영역',
    bandItemHelp: '데이터 항목마다 이 행 묶음을 반복',
    bandBeforeData: '전체 데이터 앞',
    bandBeforeDataHelp: '첫 출력 페이지에 한 번 · 제목이나 안내',
    bandPageStart: '페이지별 데이터 앞',
    bandPageStartHelp: '표시할 페이지마다 · 반복 열 제목',
    bandGroupStart: '그룹별 데이터 앞',
    bandGroupStartHelp: '각 그룹의 첫 항목 앞 · 그룹명',
    bandGroupEnd: '그룹별 데이터 뒤',
    bandGroupEndHelp: '각 그룹의 마지막 항목 뒤 · 그룹 소계',
    bandAfterData: '전체 데이터 뒤',
    bandAfterDataHelp: '마지막 항목 뒤에 한 번 · 최종 합계',
    bandPageEnd: '페이지별 데이터 뒤',
    bandPageEndHelp: '표시할 페이지마다 · 페이지 소계나 바닥글',
    bandRow: '행',
    bandMenuTitle: '{from}~{to}행 표시 방식 선택',
    bandRowOne: '{row}행',
    bandRowRange: '{from}~{to}행',
    bandRepeatOnBreak: '이월 시 다시 표시',
    bandNeedsItem: '데이터 반복 영역은 정확히 하나 있어야 합니다.',
    bandOrderError: '행 구간은 전체 데이터 앞, 페이지별 데이터 앞, 그룹별 데이터 앞, 데이터 반복 영역, 그룹별 데이터 뒤, 전체 데이터 뒤, 페이지별 데이터 뒤 순서여야 합니다.',
    bandRangeOrder: '시작 행은 종료 행보다 클 수 없습니다.',
    bandNeedsGroupBy: '그룹 구간을 쓰려면 그룹 기준을 먼저 설정해 주세요.',
    outputPage: '출력 페이지',
    outputResult: '출력 결과 보기',
    gridStructureEdit: '행 구조 편집',
    flowAreaGuide: '흐름 영역 끝',
    planError: '페이지 계획 오류',
    planErrorLocate: '문제 위치 보기',
    pagePlacementSection: '표시 페이지',
    pagePlacementMode: '배치',
    pagePlacementAbsolute: '지정 위치',
    pagePlacementAfter: '다른 요소 뒤에 이어서',
    pagePlacementPages: '표시 페이지',
    pagesAll: '모든 페이지',
    pagesFirst: '첫 페이지',
    pagesContinuation: '이어지는 페이지',
    pagesNonFinal: '마지막 제외',
    pagesLast: '마지막 페이지',
    afterTarget: '대상 요소',
    afterGap: '간격(mm)',
    afterNoTarget: '이어서 배치할 대상 요소가 없습니다.',
    cellName: '셀 이름',
    cellNameNone: '이름 없음',
    repeatFieldHint: '항목의 값 이름',
    cellSource: '값 종류',
    cellSourceText: '직접 입력',
    cellSourceParameter: '파라미터',
    cellSourceFormula: '수식',
    merge: '병합',
    columnKey: '데이터 키',
    src: '경로',
    backgroundColor: '배경색',
    fontColor: '글자색',
    borderColor: '테두리색',
    borderWidth: '테두리 굵기',
    colorNone: '없음',
    opacity: '투명도',
    hue: '색상',
    saveColor: '현재 색 저장',
    style: '스타일',
    previewLoading: 'PDF를 생성하고 있습니다…',
    previewError: 'PDF 생성에 실패했습니다.',
    pdfTitle: 'PDF 미리보기',
    elementKind: '종류',
    typeText: '텍스트',
    typeGrid: '그리드',
    typeImage: '이미지',
    typeField: '입력 필드',
    alignLeft: '왼쪽',
    alignCenter: '가운데',
    alignRight: '오른쪽',
    shape: '도형',
    shapeRect: '사각형',
    shapeLine: '선',
    shapeEllipse: '타원',
    shapePolygon: '다각형',
    shapeTriangle: '삼각형',
    shapePentagon: '오각형',
    shapeHexagon: '육각형',
    sides: '변 수',
    bold: '굵게',
    italic: '기울임',
    underline: '밑줄',
    strikethrough: '취소선',
    verticalAlignment: '세로 정렬',
    alignTop: '위',
    alignMiddle: '가운데',
    alignBottom: '아래',
    lineHeight: '줄 간격',
    characterSpacing: '글자 간격',
    verticalWriting: '세로쓰기',
    styleText: '텍스트',
    styleBackground: '배경',
    styleBorder: '테두리',
    borderShape: '형태',
    /* 선은 테두리를 두르는 게 아니라 선 자체가 굵기·색·모양을 갖습니다  */
    /* 이미지 업로드: 파일을 base64로 저장하며 URL 입력은 제공하지 않습니다. */
    imageModalTitle: '이미지 선택',
    imagePick: '이미지 업로드',
    imageReuse: '등록된 이미지',
    imageNone: '선택된 이미지 없음',
    imageSizeHint: '최대 {max}. 업로드한 이미지는 양식 파일에 포함됩니다',
    imageEmptyReuse: '등록된 이미지가 없습니다',
    imageChange: '이미지 변경',
    imageTooLarge: '이미지 용량 초과 — 최대 {max} (선택한 파일 {size})',
    imageNotImage: '이미지 파일이 아닙니다',
    imageReadFailed: '파일을 읽을 수 없습니다',
    /* 이미지 요소의 고정 소스와 파라미터 소스 설정. */
    imageMode: '이미지 방식',
    imageFixed: '고정 이미지',
    imageVariable: '변동 이미지',
    imageClear: '이미지 지우기',
    styleLine: '선',
    lineColor: '선 색',
    lineAngle: '각도(°)',
    lineWidth: '선 굵기',
    lineShape: '선 모양',
    length: '길이',
    borderSolid: '실선',
    borderDashed: '파선',
    borderDotted: '점선',
    cornerRadius: '모서리 반경',
    formulaModalTitle: '수식 편집',
    apply: '적용',
    cancel: '취소',
    close: '닫기',
    formulaFunctions: '함수',
    formulaParameters: '파라미터',
    formulaQuoteHint: '문자열은 큰따옴표로 감쌉니다. 문자열 안에 큰따옴표를 넣으려면 ""처럼 두 번 씁니다.',
    formulaColumnSuggest: '열 고르기',
    syntaxError: '문법 오류',
    previewResult: '미리 계산',
    previewUnavailable: '계산 불가',
    /* 조건부 서식 */
    conditionalFormat: '조건부 서식',
    condition: '조건식',
    conditionPlaceholder: '예: amount < 0',
    conditionHint: '조건식이 참이면 지정한 색과 강조를 적용합니다. 규칙이 겹치면 아래 규칙이 우선합니다.',
    addConditionRule: '규칙 추가',
    deleteConditionRule: '규칙 삭제',
    conditionRuleUp: '위로',
    conditionRuleDown: '아래로',
    conditionEffectRequired: '규칙에는 색이나 강조가 하나 이상 필요합니다. 규칙을 지우려면 삭제 버튼을 사용하세요.',
    conditionNotBoolean: '조건식은 논리값(참/거짓)을 반환해야 합니다',
    emphasisKeep: '기본 유지',
    emphasisApply: '적용',
    emphasisClear: '해제',
    orderForward: '앞으로',
    orderBackward: '뒤로',
    sampleData: '샘플 데이터',
    sampleModalTitle: '샘플 데이터 편집',
    sampleHint: '샘플 값을 채우면 미리보기가 그 값으로 채워진 전표를 보여줍니다.',
    addParameter: '파라미터 등록',
    parameterKey: '물리명',
    parameterLabel: '논리명',
    newParameterName: '파라미터',
    parameterUsage: '사용 요소 위치',
    parameterUnused: '아직 쓰는 요소가 없습니다.',
    parameterValueType: '파라미터 타입',
    parameterFields: '하위 필드',
    parameterField: '하위 필드',
    parameterParent: '상위 파라미터',
    parameterFieldsEmpty: '하위 필드가 없습니다.',
    addParameterField: '하위 필드 추가',
    valueTypeUnset: '지정 없음 (글자)',
    valueTypeText: '글자',
    valueTypeNumber: '숫자',
    valueTypeDate: '날짜',
    valueTypeBoolean: '참/거짓',
    valueTypeImage: '이미지(Base64)',
    valueTypeList: '목록',
    parameterNew: '새 파라미터 등록',
    parameterUnpicked: '(고르지 않음)',
    columnPanelTitle: '표 열',
    keyInUse: '이미 쓰는 물리명입니다',
    invalidInput: '입력값을 적용하지 못했습니다.',
    requiredInput: '값을 입력해 주세요.',
    numberInput: '숫자를 입력해 주세요.',
    nonNegativeInput: '0 이상의 숫자를 입력해 주세요.',
    minimumInput: '{min} 이상 입력해 주세요.',
    rangeInput: '{min}~{max} 사이의 값을 입력해 주세요.',
    paperAreaError: '용지 크기는 여백의 합보다 커야 합니다.',
    marginAreaError: '마주 보는 여백의 합은 용지 크기보다 작아야 합니다.',
    mergeOutOfGrid: '병합 범위가 그리드를 벗어납니다.',
    mergeCrossRepeat: '데이터 반복 영역의 안과 밖을 함께 병합할 수 없습니다.',
    mergeOverlap: '다른 셀과 겹쳐 병합할 수 없습니다.',
    repeatMergeError: '병합된 셀이 행 구간의 경계를 가로지릅니다.',
    colorFormatError: '#RRGGBB 또는 #RRGGBBAA 형식으로 입력해 주세요.',
    evenWidths: '너비 균등하게',
    addRow: '행 추가',
    confirm: '확인',
    myForms: '내 양식',
    saveAsMyForm: '내 양식으로 저장',
    myFormsList: '내 양식 목록',
    save: '저장',
    saveAsNew: '새 양식으로 저장',
    search: '검색',
    noSavedForms: '저장된 양식이 없습니다.',
    savedNotice: '내 양식에 저장했습니다.',
    formMode: '입력폼',
    jsonHint: '파라미터 이름을 키로 하는 JSON을 그대로 붙여 넣어 시험할 수 있습니다.',
    jsonInvalid: '올바른 JSON이 아닙니다',
    jsonNotObject: '맨 바깥은 객체({ }) 형태여야 합니다',
  },
  form: {
    noFile: '전표를 작성할 양식을 불러오세요.',
    parseError: '.slip 파일을 읽을 수 없습니다.',
    title: '전표 작성',
    noInputs: '이 양식에는 입력할 값이 없습니다.',
    computed: '자동 계산',
    calcError: '계산 오류',
    addRow: '행 추가',
    deleteRow: '행 삭제',
    issue: '발행',
    issued: '발행됨',
    issuedNotice: '발행된 전표는 더 이상 고칠 수 없습니다.',
    issueError: '발행하지 못했습니다.',
    reset: '입력 지우기',
    previewLoading: 'PDF를 생성하고 있습니다…',
    previewError: 'PDF 생성에 실패했습니다.',
    pdfTitle: 'PDF 미리보기',
    /* 변동 이미지 입력  */
    imageUpload: '이미지 선택',
    imageClear: '이미지 지우기',
    imageNone: '선택된 이미지 없음',
    imageTooLarge: '이미지 용량 초과 — 최대 {max} (선택한 파일 {size})',
    imageNotImage: '이미지 파일이 아닙니다',
    imageReadFailed: '파일을 읽을 수 없습니다',
  },
  storage: {
    ioError: '저장소 작업에 실패했습니다.',
    notFound: '저장된 파일이 없습니다',
    badCursor: '잘못된 목록 커서입니다',
    noFileSelected: '선택된 파일이 없습니다.',
    pickCancelled: '파일 선택이 취소되었습니다.',
    deleteUnsupported: '로컬 파일 저장소는 삭제를 지원하지 않습니다.',
    listUnsupported: '로컬 파일 저장소는 목록 조회를 지원하지 않습니다.',
    noMatchingKey: '복호화에 실패했습니다. 일치하는 키가 없습니다',
  },
  preset: {
    registrationNo: '등록번호',
    company: '상호',
    personName: '성명',
    address: '주소',
    titleElement: '제목',
    tradeDate: '거래일자',
    supplierInfo: '공급자 정보',
    itemsTable: '품목표',
    items: '품목',
    itemName: '품명',
    spec: '규격',
    quantity: '수량',
    unitPrice: '단가',
    amount: '금액',
    totalAmount: '합계금액',
    footer: '맺음말',
    tradeFooterText: '위와 같이 거래합니다.',
    invoiceDate: '청구일자',
    invoiceItems: '청구 항목',
    item: '항목',
    billerInfo: '청구인 정보',
    invoiceItemsTable: '청구 항목표',
    amountDue: '청구금액',
    invoiceFooterText: '위 금액을 청구합니다.',
  },
};

/** 모든 언어 사전이 공유하는 문구 구조. */
export type SlipStrings = typeof ko;

const en: SlipStrings = {
  viewer: {
    noFile: 'No .slip file to display.',
    loading: 'Generating PDF…',
    parseError: 'Could not read the .slip file.',
    renderError: 'PDF rendering failed.',
    pdfTitle: 'PDF preview',
  },
  designer: {
    noTemplate: 'Load a template to start.',
    parseError: 'Could not read the .slip file.',
    onlyTemplate: 'The designer can only edit template files.',
    addText: 'Text',
    addGrid: 'Grid',
    addImage: 'Image',
    addField: 'Field',
    addBarcode: 'Barcode',
    delete: 'Delete',
    copy: 'Copy',
    paste: 'Paste',
    undo: 'Undo',
    redo: 'Redo',
    preview: 'Preview',
    edit: 'Edit',
    preset: 'Presets',
    presetTradeStatement: 'Transaction statement',
    presetInvoice: 'Invoice',
    addPage: 'Add page',
    deletePage: 'Delete page',
    showBadges: 'Show element types',
    grid: 'Grid lines',
    gridNone: 'No grid lines',
    gridGap: 'Grid line spacing',
    gridColor: 'Grid line color',
    colorGray: 'Gray',
    colorBlue: 'Blue',
    colorRed: 'Red',
    colorGreen: 'Green',
    pageMoveForward: 'Move page forward',
    pageMoveBackward: 'Move page backward',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    sidebarPages: 'Pages',
    pageLabel: 'Page {n}',
    pageSettings: 'Page settings',
    pageName: 'Name',
    pageKey: 'Key',
    pageNumberShow: 'Show number',
    pageNumberPosition: 'Number position',
    pagePosBottomLeft: 'Bottom left',
    pagePosBottomCenter: 'Bottom center',
    pagePosBottomRight: 'Bottom right',
    pagePosTopLeft: 'Top left',
    pagePosTopCenter: 'Top center',
    pagePosTopRight: 'Top right',
    pageOrder: 'Page order',
    sidebarElements: 'Elements',
    sidebarParameters: 'Parameters',
    typeBarcode: 'Barcode',
    /* Barcode element editing  */
    barcodeKind: 'Barcode type',
    barcodeValue: 'Barcode value',
    barcodeWarnDigits: '{name} must be {n} digits',
    barcodeWarnCode39: 'CODE39 allows only uppercase letters, digits, and - . $ / + % space',
    expandRow: 'Expand',
    collapseRow: 'Collapse',
    /* Value/formula cell rows when a grid is expanded in the element list  */
    gridCellAt: 'Row {r}, Col {c}',
    /* Element grouping  */
    groupSelection: 'Multiple elements',
    selectedCount: 'Selected',
    groupElements: 'Group',
    ungroupElements: 'Ungroup',
    panelBasic: 'Basic',
    panelLayout: 'Layout',
    panelStructure: 'Structure',
    panelValue: 'Value',
    panelPaper: 'Paper',
    panelPageNumber: 'Page number',
    formSettings: 'Form settings',
    formTitle: 'Title',
    paperSize: 'Paper size',
    paperCustom: 'Custom',
    /* Paper size supply/save  */
    paperSaveThis: 'Save this size',
    paperSizeName: 'Size name',
    orientation: 'Orientation',
    portrait: 'Portrait',
    landscape: 'Landscape',
    margin: 'Margins',
    marginTop: 'Top',
    marginRight: 'Right',
    marginBottom: 'Bottom',
    marginLeft: 'Left',
    name: 'Name',
    anchor: 'Anchor',
    anchorTL: 'Top left',
    anchorT: 'Top',
    anchorTR: 'Top right',
    anchorL: 'Left',
    anchorC: 'Center',
    anchorR: 'Right',
    anchorBL: 'Bottom left',
    anchorB: 'Bottom',
    anchorBR: 'Bottom right',
    width: 'Width',
    height: 'Height',
    content: 'Content',
    parameter: 'Parameter',
    formula: 'Formula',
    fontName: 'Font',
    fontDefault: 'Default font',
    fontSize: 'Font size',
    alignment: 'Align',
    rows: 'Rows',
    columns: 'Columns',
    cell: 'Selected cell',
    gridBack: 'Grid settings',
    /** Grid  */
    rowHeight: 'Row height',
    columnWidth: 'Column width',
    overflow: 'Long text',
    overflowInherit: 'Use grid setting',
    overflowClip: 'Hide overflow',
    overflowShrink: 'Reduce font size',
    repeatSection: 'Repeat',
    repeatOn: 'Enabled',
    repeatMaxItems: 'Maximum items',
    repeatMaxItemsNone: 'No limit',
    advancedSettings: 'Advanced settings',
    selectRole: 'Select display behavior',
    repeatCellHint: 'repeats',
    paginationMode: 'Page mode',
    paginationAuto: 'Auto grow',
    paginationFixed: 'Fixed pages',
    minItems: 'Minimum items shown',
    itemsPerPage: 'Items per page',
    groupBy: 'Group by',
    groupByNone: 'Not used',
    bandSection: 'Row bands',
    gridCommandSection: 'Quick setup',
    gridCommandManual: 'Manual editing',
    gridCommandHeaderName: 'Header',
    gridCommandGroupSubtotalName: 'Group subtotal',
    gridCommandPageSubtotalName: 'Page subtotal',
    gridCommandFinalTotalName: 'Final total',
    gridCommandPreview: 'Result to add',
    gridCommandField: 'Field to total',
    gridCommandFieldMissing: 'No numeric field',
    gridCommandLocation: 'Position',
    gridCommandDisplay: 'Display',
    gridCommandCalculation: 'Calculation',
    gridCommandNone: 'None',
    gridCommandEachGroup: 'Each group',
    gridCommandOnce: 'Once',
    gridCommandGroupCalculation: '{field} total for each group',
    gridCommandPageCalculation: '{field} total for each page',
    gridCommandFinalCalculation: '{field} total for all items',
    gridCommandApply: 'Add this row',
    gridCommandGroupRequired: 'Choose a group field in Advanced settings first.',
    gridCommandNumberRequired: 'Add a numeric field to the list parameter first.',
    bandRole: 'Display behavior',
    bandFromRow: 'Start row',
    bandToRow: 'End row',
    bandItem: 'Data repeat area',
    bandItemHelp: 'Repeats these rows once per data item',
    bandBeforeData: 'Before all data',
    bandBeforeDataHelp: 'Once on the first output page · title or introductory note',
    bandPageStart: 'Before data on each page',
    bandPageStartHelp: 'On each selected output page · repeating column headings',
    bandGroupStart: 'Before each group',
    bandGroupStartHelp: 'Before the first item in each group · group heading',
    bandGroupEnd: 'After each group',
    bandGroupEndHelp: 'After the last item in each group · group subtotal',
    bandAfterData: 'After all data',
    bandAfterDataHelp: 'Once after the final item · final total',
    bandPageEnd: 'After data on each page',
    bandPageEndHelp: 'On each selected output page · page subtotal or footer',
    bandRow: 'Row',
    bandMenuTitle: 'Choose how rows {from}-{to} are displayed',
    bandRowOne: 'Row {row}',
    bandRowRange: 'Rows {from}-{to}',
    bandRepeatOnBreak: 'Show again after page break',
    bandNeedsItem: 'Exactly one data repeat area is required.',
    bandOrderError: 'Row bands must follow the order: before all data, before page data, before each group, data repeat area, after each group, after all data, after page data.',
    bandRangeOrder: 'The start row cannot be greater than the end row.',
    bandNeedsGroupBy: 'Set the group-by fields before using group bands.',
    outputPage: 'Output page',
    outputResult: 'View output',
    gridStructureEdit: 'Edit row structure',
    flowAreaGuide: 'End of flow area',
    planError: 'Page plan error',
    planErrorLocate: 'Show problem',
    pagePlacementSection: 'Display pages',
    pagePlacementMode: 'Placement',
    pagePlacementAbsolute: 'Fixed position',
    pagePlacementAfter: 'After another element',
    pagePlacementPages: 'Pages',
    pagesAll: 'All pages',
    pagesFirst: 'First page',
    pagesContinuation: 'Continuation pages',
    pagesNonFinal: 'All but last',
    pagesLast: 'Last page',
    afterTarget: 'Target element',
    afterGap: 'Gap (mm)',
    afterNoTarget: 'No element is available to follow.',
    cellName: 'Cell name',
    cellNameNone: 'No name',
    repeatFieldHint: 'field name of the item',
    cellSource: 'Value source',
    cellSourceText: 'Direct input',
    cellSourceParameter: 'Parameter',
    cellSourceFormula: 'Formula',
    merge: 'Merge',
    columnKey: 'Data key',
    src: 'Source',
    backgroundColor: 'Background',
    fontColor: 'Text color',
    borderColor: 'Border color',
    borderWidth: 'Border width',
    colorNone: 'None',
    opacity: 'Opacity',
    hue: 'Hue',
    saveColor: 'Save current color',
    style: 'Style',
    previewLoading: 'Generating PDF…',
    previewError: 'Failed to generate the PDF.',
    pdfTitle: 'PDF preview',
    elementKind: 'Kind',
    typeText: 'Text',
    typeGrid: 'Grid',
    typeImage: 'Image',
    typeField: 'Input field',
    alignLeft: 'Left',
    alignCenter: 'Center',
    alignRight: 'Right',
    shape: 'Shape',
    shapeRect: 'Rectangle',
    shapeLine: 'Line',
    shapeEllipse: 'Ellipse',
    shapePolygon: 'Polygon',
    shapeTriangle: 'Triangle',
    shapePentagon: 'Pentagon',
    shapeHexagon: 'Hexagon',
    sides: 'Sides',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    verticalAlignment: 'Vertical align',
    alignTop: 'Top',
    alignMiddle: 'Middle',
    alignBottom: 'Bottom',
    lineHeight: 'Line height',
    characterSpacing: 'Letter spacing',
    verticalWriting: 'Vertical text',
    styleText: 'Text',
    styleBackground: 'Background',
    styleBorder: 'Border',
    borderShape: 'Line style',
    imageModalTitle: 'Select image',
    imagePick: 'Upload image',
    imageReuse: 'Registered images',
    imageNone: 'No image selected',
    imageSizeHint: 'Up to {max}. Uploaded images are stored in the template file.',
    imageEmptyReuse: 'No registered images',
    imageChange: 'Change image',
    imageTooLarge: 'Image too large — max {max} (selected file is {size})',
    imageNotImage: 'Not an image file',
    imageReadFailed: 'Could not read the file',
    /* Fixed and parameter-bound image sources. */
    imageMode: 'Image mode',
    imageFixed: 'Fixed image',
    imageVariable: 'Variable image',
    imageClear: 'Clear image',
    styleLine: 'Line',
    lineColor: 'Line color',
    lineAngle: 'Angle (°)',
    lineWidth: 'Line width',
    lineShape: 'Line style',
    length: 'Length',
    borderSolid: 'Solid',
    borderDashed: 'Dashed',
    borderDotted: 'Dotted',
    cornerRadius: 'Corner radius',
    formulaModalTitle: 'Edit formula',
    apply: 'Apply',
    cancel: 'Cancel',
    close: 'Close',
    formulaFunctions: 'Functions',
    formulaParameters: 'Parameters',
    formulaQuoteHint: 'Wrap text in double quotes. To include a quote inside text, type it twice ("").',
    formulaColumnSuggest: 'Pick a column',
    syntaxError: 'Syntax error',
    previewResult: 'Preview',
    previewUnavailable: 'Cannot evaluate',
    /* Conditional format */
    conditionalFormat: 'Conditional format',
    condition: 'Condition',
    conditionPlaceholder: 'e.g. amount < 0',
    conditionHint: 'Colors and emphasis apply when the condition is true. When rules overlap, the lower rule wins.',
    addConditionRule: 'Add rule',
    deleteConditionRule: 'Delete rule',
    conditionRuleUp: 'Move up',
    conditionRuleDown: 'Move down',
    conditionEffectRequired: 'A rule needs at least one color or emphasis. Use the delete button to remove the rule.',
    conditionNotBoolean: 'The condition must return TRUE or FALSE',
    emphasisKeep: 'Keep base',
    emphasisApply: 'Apply',
    emphasisClear: 'Clear',
    orderForward: 'Move forward',
    orderBackward: 'Move backward',
    sampleData: 'Sample data',
    sampleModalTitle: 'Edit sample data',
    sampleHint: 'Fill in sample values and the preview shows a voucher filled with them.',
    addParameter: 'Add parameter',
    parameterKey: 'Key',
    parameterLabel: 'Label',
    newParameterName: 'Parameter',
    parameterUsage: 'Used by',
    parameterUnused: 'Not used by any element yet.',
    parameterValueType: 'Parameter type',
    parameterFields: 'Item fields',
    parameterField: 'Item field',
    parameterParent: 'Parent parameter',
    parameterFieldsEmpty: 'No item fields yet.',
    addParameterField: 'Add item field',
    valueTypeUnset: 'Unset (text)',
    valueTypeText: 'Text',
    valueTypeNumber: 'Number',
    valueTypeDate: 'Date',
    valueTypeBoolean: 'True/false',
    valueTypeImage: 'Image (Base64)',
    valueTypeList: 'List',
    parameterNew: 'Register new parameter',
    parameterUnpicked: '(not picked)',
    columnPanelTitle: 'Table column',
    keyInUse: 'That key is already in use',
    invalidInput: 'The value could not be applied.',
    requiredInput: 'Enter a value.',
    numberInput: 'Enter a number.',
    nonNegativeInput: 'Enter a number greater than or equal to 0.',
    minimumInput: 'Enter {min} or greater.',
    rangeInput: 'Enter a value from {min} to {max}.',
    paperAreaError: 'The paper size must be larger than the combined margins.',
    marginAreaError: 'Opposing margins must total less than the paper size.',
    mergeOutOfGrid: 'The merged area extends outside the grid.',
    mergeCrossRepeat: 'Cells inside and outside the data repeat area cannot be merged together.',
    mergeOverlap: 'The merged area overlaps another cell.',
    repeatMergeError: 'A merged cell crosses a row band boundary.',
    colorFormatError: 'Enter #RRGGBB or #RRGGBBAA.',
    evenWidths: 'Equal widths',
    addRow: 'Add row',
    confirm: 'OK',
    myForms: 'My forms',
    saveAsMyForm: 'Save to my forms',
    myFormsList: 'My forms',
    save: 'Save',
    saveAsNew: 'Save as a new form',
    search: 'Search',
    noSavedForms: 'No saved forms yet.',
    savedNotice: 'Saved to my forms.',
    formMode: 'Form',
    jsonHint: 'Paste JSON keyed by parameter names to test it directly.',
    jsonInvalid: 'Not valid JSON',
    jsonNotObject: 'The top level must be an object ({ })',
  },
  form: {
    noFile: 'Load a template to fill in a slip.',
    parseError: 'Could not read the .slip file.',
    title: 'Fill in slip',
    noInputs: 'This template has no values to fill in.',
    computed: 'Calculated',
    calcError: 'Calculation error',
    addRow: 'Add row',
    deleteRow: 'Delete row',
    issue: 'Issue',
    issued: 'Issued',
    issuedNotice: 'An issued slip can no longer be edited.',
    issueError: 'Could not issue the slip.',
    reset: 'Clear values',
    previewLoading: 'Generating PDF…',
    previewError: 'Failed to generate the PDF.',
    pdfTitle: 'PDF preview',
    /* Variable image input  */
    imageUpload: 'Select image',
    imageClear: 'Clear image',
    imageNone: 'No image selected',
    imageTooLarge: 'Image too large — max {max} (selected file is {size})',
    imageNotImage: 'Not an image file',
    imageReadFailed: 'Could not read the file',
  },
  storage: {
    ioError: 'Storage operation failed.',
    notFound: 'No saved file',
    badCursor: 'Invalid list cursor',
    noFileSelected: 'No file was selected.',
    pickCancelled: 'File selection was cancelled.',
    deleteUnsupported: 'Local file storage does not support delete.',
    listUnsupported: 'Local file storage does not support listing.',
    noMatchingKey: 'Decryption failed — no matching key',
  },
  preset: {
    registrationNo: 'Registration no.',
    company: 'Company',
    personName: 'Name',
    address: 'Address',
    titleElement: 'Title',
    tradeDate: 'Transaction date',
    supplierInfo: 'Supplier info',
    itemsTable: 'Items table',
    items: 'Items',
    itemName: 'Item name',
    spec: 'Spec',
    quantity: 'Qty',
    unitPrice: 'Unit price',
    amount: 'Amount',
    totalAmount: 'Total amount',
    footer: 'Closing note',
    tradeFooterText: 'The above transaction is confirmed.',
    invoiceDate: 'Invoice date',
    invoiceItems: 'Invoice items',
    item: 'Item',
    billerInfo: 'Biller info',
    invoiceItemsTable: 'Invoice items table',
    amountDue: 'Amount due',
    invoiceFooterText: 'Please pay the amount above.',
  },
};

const ja: SlipStrings = {
  viewer: {
    noFile: '表示する .slip ファイルがありません。',
    loading: 'PDF を生成しています…',
    parseError: '.slip ファイルを読み込めません。',
    renderError: 'PDF のレンダリングに失敗しました。',
    pdfTitle: 'PDF プレビュー',
  },
  designer: {
    noTemplate: 'テンプレートを読み込んでください。',
    parseError: '.slip ファイルを読み込めません。',
    onlyTemplate: 'デザイナーはテンプレート（template）ファイルのみ編集できます。',
    addText: 'テキスト',
    addGrid: 'グリッド',
    addImage: '画像',
    addField: 'フィールド',
    addBarcode: 'バーコード',
    delete: '削除',
    copy: 'コピー',
    paste: '貼り付け',
    undo: '元に戻す',
    redo: 'やり直し',
    preview: 'プレビュー',
    edit: '編集',
    preset: 'プリセット',
    presetTradeStatement: '取引明細書',
    presetInvoice: '請求書',
    addPage: 'ページ追加',
    deletePage: 'ページ削除',
    showBadges: '要素を確認',
    grid: '方眼',
    gridNone: '方眼なし',
    gridGap: '方眼の間隔',
    gridColor: '方眼の色',
    colorGray: 'グレー',
    colorBlue: '青',
    colorRed: '赤',
    colorGreen: '緑',
    pageMoveForward: 'ページを前へ',
    pageMoveBackward: 'ページを後ろへ',
    prevPage: '前のページ',
    nextPage: '次のページ',
    sidebarPages: 'ページ',
    pageLabel: '{n}ページ',
    pageSettings: 'ページ設定',
    pageName: '名前',
    pageKey: '物理名',
    pageNumberShow: '番号を表示',
    pageNumberPosition: '番号の位置',
    pagePosBottomLeft: '下 左',
    pagePosBottomCenter: '下 中央',
    pagePosBottomRight: '下 右',
    pagePosTopLeft: '上 左',
    pagePosTopCenter: '上 中央',
    pagePosTopRight: '上 右',
    pageOrder: 'ページ順序',
    sidebarElements: '要素',
    sidebarParameters: 'パラメータ',
    typeBarcode: 'バーコード',
    /* 바코드 요소 편집  */
    barcodeKind: 'バーコードの種類',
    barcodeValue: 'バーコードの値',
    barcodeWarnDigits: '{name}は数字 {n} 桁である必要があります',
    barcodeWarnCode39: 'CODE39 は大文字・数字・一部の記号（- . $ / + % 空白）のみ使えます',
    expandRow: '展開',
    collapseRow: '折りたたむ',
    /* 요소 목록에서 그리드를 펼쳤을 때 값·수식 셀 줄  */
    gridCellAt: '{r}行{c}列',
    /* 요소 그룹화  */
    groupSelection: '複数の要素',
    selectedCount: '選択数',
    groupElements: 'グループ化',
    ungroupElements: 'グループ解除',
    panelBasic: '基本',
    panelLayout: '配置',
    panelStructure: '構造',
    panelValue: '値',
    panelPaper: '用紙',
    panelPageNumber: 'ページ番号',
    formSettings: 'テンプレート設定',
    formTitle: 'タイトル',
    paperSize: '用紙サイズ',
    paperCustom: 'カスタム入力',
    /* 용지 공급·저장  */
    paperSaveThis: 'このサイズを保存',
    paperSizeName: '用紙名',
    orientation: '向き',
    portrait: '縦',
    landscape: '横',
    margin: '余白',
    marginTop: '上',
    marginRight: '右',
    marginBottom: '下',
    marginLeft: '左',
    name: '名前',
    anchor: '基準点',
    anchorTL: '左上',
    anchorT: '上',
    anchorTR: '右上',
    anchorL: '左',
    anchorC: '中央',
    anchorR: '右',
    anchorBL: '左下',
    anchorB: '下',
    anchorBR: '右下',
    width: '幅',
    height: '高さ',
    content: '内容',
    parameter: 'パラメータ',
    formula: '数式',
    fontName: 'フォント',
    fontDefault: '既定フォント',
    fontSize: '文字サイズ',
    alignment: '揃え',
    rows: '行',
    columns: '列',
    cell: '選択セル',
    gridBack: 'グリッド設定',
    /** 그리드  */
    rowHeight: '行の高さ',
    columnWidth: '列の幅',
    overflow: '長い内容の表示',
    overflowInherit: 'グリッド設定を使用',
    overflowClip: 'はみ出した部分を隠す',
    overflowShrink: '文字サイズを縮小',
    repeatSection: '繰り返し',
    repeatOn: '使用',
    repeatMaxItems: '最大項目数',
    repeatMaxItemsNone: '上限なし',
    advancedSettings: '詳細設定',
    selectRole: '表示方法を選択',
    repeatCellHint: '繰り返し',
    paginationMode: 'ページ方式',
    paginationAuto: '自動拡張',
    paginationFixed: '固定ページ',
    minItems: '最小表示項目数',
    itemsPerPage: '1ページの項目数',
    groupBy: 'グループ基準',
    groupByNone: '使用しない',
    bandSection: '行範囲',
    gridCommandSection: 'かんたん設定',
    gridCommandManual: '個別編集',
    gridCommandHeaderName: 'ヘッダー',
    gridCommandGroupSubtotalName: 'グループ小計',
    gridCommandPageSubtotalName: 'ページ小計',
    gridCommandFinalTotalName: '最終合計',
    gridCommandPreview: '追加結果',
    gridCommandField: '集計するフィールド',
    gridCommandFieldMissing: '数値フィールドなし',
    gridCommandLocation: '位置',
    gridCommandDisplay: '表示',
    gridCommandCalculation: '計算',
    gridCommandNone: 'なし',
    gridCommandEachGroup: '各グループ',
    gridCommandOnce: '1回',
    gridCommandGroupCalculation: '各グループの{field}合計',
    gridCommandPageCalculation: '各ページの{field}合計',
    gridCommandFinalCalculation: '全項目の{field}合計',
    gridCommandApply: 'この行を追加',
    gridCommandGroupRequired: '先に詳細設定でグループ基準を選択してください。',
    gridCommandNumberRequired: 'リストパラメーターに数値フィールドを追加してください。',
    bandRole: '表示方法',
    bandFromRow: '開始行',
    bandToRow: '終了行',
    bandItem: 'データ繰り返し領域',
    bandItemHelp: 'データ1件ごとにこの行範囲を繰り返す',
    bandBeforeData: '全データの前',
    bandBeforeDataHelp: '最初の出力ページに1回 · タイトルや案内',
    bandPageStart: 'ページごとのデータ前',
    bandPageStartHelp: '表示対象の各ページ · 繰り返す列見出し',
    bandGroupStart: 'グループごとのデータ前',
    bandGroupStartHelp: '各グループの最初の項目前 · グループ名',
    bandGroupEnd: 'グループごとのデータ後',
    bandGroupEndHelp: '各グループの最後の項目後 · グループ小計',
    bandAfterData: '全データの後',
    bandAfterDataHelp: '最後の項目後に1回 · 最終合計',
    bandPageEnd: 'ページごとのデータ後',
    bandPageEndHelp: '表示対象の各ページ · ページ小計やフッター',
    bandRow: '行',
    bandMenuTitle: '{from}~{to}行の表示方法を選択',
    bandRowOne: '{row}行',
    bandRowRange: '{from}~{to}行',
    bandRepeatOnBreak: 'ページ繰り越し時に再表示',
    bandNeedsItem: 'データ繰り返し領域はちょうど 1 つ必要です。',
    bandOrderError: '行範囲は全データの前、ページごとのデータ前、グループごとのデータ前、データ繰り返し領域、グループごとのデータ後、全データの後、ページごとのデータ後の順序にしてください。',
    bandRangeOrder: '開始行は終了行より大きくできません。',
    bandNeedsGroupBy: 'グループ範囲を使うには先にグループ基準を設定してください。',
    outputPage: '出力ページ',
    outputResult: '出力結果を表示',
    gridStructureEdit: '行構成を編集',
    flowAreaGuide: 'フロー領域の終端',
    planError: 'ページ計画エラー',
    planErrorLocate: '問題箇所を表示',
    pagePlacementSection: '表示ページ',
    pagePlacementMode: '配置',
    pagePlacementAbsolute: '指定位置',
    pagePlacementAfter: '他の要素の後に続けて',
    pagePlacementPages: '表示ページ',
    pagesAll: 'すべてのページ',
    pagesFirst: '最初のページ',
    pagesContinuation: '続きのページ',
    pagesNonFinal: '最後を除く',
    pagesLast: '最後のページ',
    afterTarget: '対象要素',
    afterGap: '間隔(mm)',
    afterNoTarget: '続けて配置できる対象要素がありません。',
    cellName: 'セル名',
    cellNameNone: '名前なし',
    repeatFieldHint: '項目の値名',
    cellSource: '値の種類',
    cellSourceText: '直接入力',
    cellSourceParameter: 'パラメータ',
    cellSourceFormula: '数式',
    merge: '結合',
    columnKey: 'データキー',
    src: 'パス',
    backgroundColor: '背景色',
    fontColor: '文字色',
    borderColor: '枠線の色',
    borderWidth: '枠線の太さ',
    colorNone: 'なし',
    opacity: '不透明度',
    hue: '色相',
    saveColor: '現在の色を保存',
    style: 'スタイル',
    previewLoading: 'PDF を生成しています…',
    previewError: 'PDF の生成に失敗しました。',
    pdfTitle: 'PDF プレビュー',
    elementKind: '種類',
    typeText: 'テキスト',
    typeGrid: 'グリッド',
    typeImage: '画像',
    typeField: '入力フィールド',
    alignLeft: '左',
    alignCenter: '中央',
    alignRight: '右',
    shape: '図形',
    shapeRect: '四角形',
    shapeLine: '線',
    shapeEllipse: '楕円',
    shapePolygon: '多角形',
    shapeTriangle: '三角形',
    shapePentagon: '五角形',
    shapeHexagon: '六角形',
    sides: '辺の数',
    bold: '太字',
    italic: '斜体',
    underline: '下線',
    strikethrough: '取り消し線',
    verticalAlignment: '縦方向の揃え',
    alignTop: '上',
    alignMiddle: '中央',
    alignBottom: '下',
    lineHeight: '行間',
    characterSpacing: '文字間',
    verticalWriting: '縦書き',
    styleText: 'テキスト',
    styleBackground: '背景',
    styleBorder: '枠線',
    borderShape: '形状',
    /* 선은 테두리를 두르는 게 아니라 선 자체가 굵기·색·모양을 갖습니다  */
    /* 이미지 업로드: 파일을 base64로 저장하며 URL 입력은 제공하지 않습니다. */
    imageModalTitle: '画像を選択',
    imagePick: '画像をアップロード',
    imageReuse: '登録済みの画像',
    imageNone: '選択された画像がありません',
    imageSizeHint: '最大 {max}。アップロードした画像はテンプレートファイルに含まれます',
    imageEmptyReuse: '登録済みの画像がありません',
    imageChange: '画像を変更',
    imageTooLarge: '画像の容量超過 — 最大 {max}（選択したファイル {size}）',
    imageNotImage: '画像ファイルではありません',
    imageReadFailed: 'ファイルを読み込めません',
    /* 이미지 요소의 고정 소스와 파라미터 소스 설정. */
    imageMode: '画像の方式',
    imageFixed: '固定画像',
    imageVariable: '変動画像',
    imageClear: '画像を消す',
    styleLine: '線',
    lineColor: '線の色',
    lineAngle: '角度(°)',
    lineWidth: '線の太さ',
    lineShape: '線の形状',
    length: '長さ',
    borderSolid: '実線',
    borderDashed: '破線',
    borderDotted: '点線',
    cornerRadius: '角の丸み',
    formulaModalTitle: '数式を編集',
    apply: '適用',
    cancel: 'キャンセル',
    close: '閉じる',
    formulaFunctions: '関数',
    formulaParameters: 'パラメータ',
    formulaQuoteHint: '文字列は二重引用符で囲みます。文字列の中に二重引用符を入れるには "" のように 2 回書きます。',
    formulaColumnSuggest: '列を選ぶ',
    syntaxError: '構文エラー',
    previewResult: '計算プレビュー',
    previewUnavailable: '計算できません',
    /* 条件付き書式 */
    conditionalFormat: '条件付き書式',
    condition: '条件式',
    conditionPlaceholder: '例: amount < 0',
    conditionHint: '条件式が真のとき指定した色と強調を適用します。ルールが重なる場合は下のルールが優先されます。',
    addConditionRule: 'ルールを追加',
    deleteConditionRule: 'ルールを削除',
    conditionRuleUp: '上へ',
    conditionRuleDown: '下へ',
    conditionEffectRequired: 'ルールには色または強調が 1 つ以上必要です。ルールを消すには削除ボタンを使ってください。',
    conditionNotBoolean: '条件式は論理値(TRUE/FALSE)を返す必要があります',
    emphasisKeep: '基本のまま',
    emphasisApply: '適用',
    emphasisClear: '解除',
    orderForward: '前へ',
    orderBackward: '後ろへ',
    sampleData: 'サンプルデータ',
    sampleModalTitle: 'サンプルデータの編集',
    sampleHint: 'サンプル値を入れると、プレビューがその値で埋めた伝票を表示します。',
    addParameter: 'パラメータを登録',
    parameterKey: '物理名',
    parameterLabel: '論理名',
    newParameterName: 'パラメータ',
    parameterUsage: '使用要素の位置',
    parameterUnused: 'まだ使っている要素がありません。',
    parameterValueType: 'パラメータタイプ',
    parameterFields: '項目フィールド',
    parameterField: '項目フィールド',
    parameterParent: '親パラメータ',
    parameterFieldsEmpty: '項目フィールドがありません。',
    addParameterField: '項目フィールドを追加',
    valueTypeUnset: '指定なし（文字）',
    valueTypeText: '文字',
    valueTypeNumber: '数値',
    valueTypeDate: '日付',
    valueTypeBoolean: '真偽',
    valueTypeImage: '画像（Base64）',
    valueTypeList: 'リスト',
    parameterNew: '新しいパラメータを登録',
    parameterUnpicked: '（選択なし）',
    columnPanelTitle: '表の列',
    keyInUse: 'すでに使われている物理名です',
    invalidInput: '入力値を適用できませんでした。',
    requiredInput: '値を入力してください。',
    numberInput: '数値を入力してください。',
    nonNegativeInput: '0以上の数値を入力してください。',
    minimumInput: '{min}以上を入力してください。',
    rangeInput: '{min}～{max}の範囲で入力してください。',
    paperAreaError: '用紙サイズは余白の合計より大きくしてください。',
    marginAreaError: '向かい合う余白の合計は用紙サイズ未満にしてください。',
    mergeOutOfGrid: '結合範囲がグリッドの外にはみ出しています。',
    mergeCrossRepeat: 'データ繰り返し領域の内側と外側をまとめて結合できません。',
    mergeOverlap: '結合範囲が別のセルと重なっています。',
    repeatMergeError: '結合セルが行範囲の境界をまたいでいます。',
    colorFormatError: '#RRGGBBまたは#RRGGBBAA形式で入力してください。',
    evenWidths: '幅を均等に',
    addRow: '行を追加',
    confirm: '確認',
    myForms: 'マイテンプレート',
    saveAsMyForm: 'マイテンプレートに保存',
    myFormsList: 'マイテンプレート一覧',
    save: '保存',
    saveAsNew: '新規テンプレートとして保存',
    search: '検索',
    noSavedForms: '保存されたテンプレートがありません。',
    savedNotice: 'マイテンプレートに保存しました。',
    formMode: '入力フォーム',
    jsonHint: 'パラメータ名をキーにした JSON をそのまま貼り付けて試せます。',
    jsonInvalid: '正しい JSON ではありません',
    jsonNotObject: '最も外側はオブジェクト（{ }）の形である必要があります',
  },
  form: {
    noFile: '伝票を作成するテンプレートを読み込んでください。',
    parseError: '.slip ファイルを読み込めません。',
    title: '伝票作成',
    noInputs: 'このテンプレートには入力する値がありません。',
    computed: '自動計算',
    calcError: '計算エラー',
    addRow: '行を追加',
    deleteRow: '行を削除',
    issue: '発行',
    issued: '発行済み',
    issuedNotice: '発行された伝票はこれ以上編集できません。',
    issueError: '発行できませんでした。',
    reset: '入力をクリア',
    previewLoading: 'PDF を生成しています…',
    previewError: 'PDF の生成に失敗しました。',
    pdfTitle: 'PDF プレビュー',
    /* 변동 이미지 입력  */
    imageUpload: '画像を選択',
    imageClear: '画像を消す',
    imageNone: '選択された画像がありません',
    imageTooLarge: '画像の容量超過 — 最大 {max}（選択したファイル {size}）',
    imageNotImage: '画像ファイルではありません',
    imageReadFailed: 'ファイルを読み込めません',
  },
  storage: {
    ioError: 'ストレージ操作に失敗しました。',
    notFound: '保存されたファイルがありません',
    badCursor: '不正な一覧カーソルです',
    noFileSelected: '選択されたファイルがありません。',
    pickCancelled: 'ファイル選択がキャンセルされました。',
    deleteUnsupported: 'ローカルファイルストレージは削除に対応していません。',
    listUnsupported: 'ローカルファイルストレージは一覧取得に対応していません。',
    noMatchingKey: '復号に失敗しました — 一致するキーがありません',
  },
  preset: {
    registrationNo: '登録番号',
    company: '商号',
    personName: '氏名',
    address: '住所',
    titleElement: 'タイトル',
    tradeDate: '取引日',
    supplierInfo: '供給者情報',
    itemsTable: '品目表',
    items: '品目',
    itemName: '品名',
    spec: '規格',
    quantity: '数量',
    unitPrice: '単価',
    amount: '金額',
    totalAmount: '合計金額',
    footer: '結びの文',
    tradeFooterText: '上記のとおり取引します。',
    invoiceDate: '請求日',
    invoiceItems: '請求項目',
    item: '項目',
    billerInfo: '請求者情報',
    invoiceItemsTable: '請求項目表',
    amountDue: '請求金額',
    invoiceFooterText: '上記の金額を請求します。',
  },
};

/** 언어별 문구 사전 전체 */
export const STRINGS: Record<SlipLocale, SlipStrings> = { ko, en, ja };

/**
 * 로케일 문자열을 지원 언어({@link SlipLocale})로 정규화합니다. 지역 코드는 제외하고
 * 언어 코드만 사용하며, 지원하지 않는 언어에는 영어를 적용합니다.
 *
 * @param locale - UI 언어 (생략하면 영어)
 * @returns 정규화된 지원 언어 코드
 */
export function normalizeLocale(locale?: string): SlipLocale {
  const language = locale?.toLowerCase().split('-')[0];
  return language && language in STRINGS ? (language as SlipLocale) : 'en';
}

/**
 * 로케일에 맞는 문구 사전을 반환합니다. 지역 코드는 제외하고 지원하지 않는 언어에는
 * 영어 문구 사전을 반환합니다.
 *
 * @param locale - UI 언어 (생략하면 영어)
 * @returns 해당 언어의 문구 사전
 */
export function getStrings(locale?: string): SlipStrings {
  return STRINGS[normalizeLocale(locale)];
}

/** 로케일에 맞는 디자이너 문구 */
export type DesignerStrings = ReturnType<typeof getStrings>['designer'];
