/**
 * UI 문구 리소스 (ADR-013/028).
 *
 * 문구는 전부 이 파일의 언어별 사전에 모으고, 컴포넌트는 `locale` 속성으로
 * 사전을 고른다 (기본 한국어). 새 문구는 반드시 두 사전에 함께 추가한다 —
 * `SlipStrings` 타입이 키 누락을 컴파일 단계에서 잡는다.
 */

/** 지원하는 UI 언어 (ADR-028) */
export type SlipLocale = 'ko' | 'en';

const ko = {
  viewer: {
    noFile: '표시할 .slip 파일이 없습니다.',
    loading: 'PDF를 생성하고 있습니다…',
    parseError: '.slip 파일을 읽을 수 없습니다.',
    renderError: 'PDF 렌더링에 실패했습니다.',
    pdfTitle: 'PDF 미리보기',
  },
  designer: {
    noTemplate: '양식을 불러오세요.',
    parseError: '.slip 파일을 읽을 수 없습니다.',
    onlyTemplate: '디자이너는 양식(template) 파일만 편집할 수 있습니다.',
    addText: '텍스트',
    addGrid: '그리드',
    addImage: '이미지',
    addField: '필드',
    delete: '삭제',
    copy: '복사',
    paste: '붙여넣기',
    undo: '되돌리기',
    redo: '다시 실행',
    preview: '미리보기',
    edit: '편집',
    preset: '프리셋',
    presetTradeStatement: '거래명세서',
    presetInvoice: '청구서',
    addPage: '페이지 추가',
    deletePage: '페이지 삭제',
    showBadges: '종류 보기',
    grid: '격자',
    gridNone: '격자 없음',
    gridGap: '격자 간격',
    gridColor: '격자 색',
    colorGray: '회색',
    colorBlue: '파랑',
    colorRed: '빨강',
    colorGreen: '초록',
    pageMoveForward: '페이지 앞으로',
    pageMoveBackward: '페이지 뒤로',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
    sidebarPages: '페이지',
    pageLabel: '{n}페이지',
    pageSettings: '페이지 설정',
    pageName: '이름',
    pageKey: '물리명',
    pageNameHint: '썸네일·목록에 번호 대신 나온다',
    pageNumberShow: '페이지 번호 표시',
    pageNumberPosition: '번호 위치',
    pagePosBottomLeft: '아래 왼쪽',
    pagePosBottomCenter: '아래 가운데',
    pagePosBottomRight: '아래 오른쪽',
    pagePosTopLeft: '위 왼쪽',
    pagePosTopCenter: '위 가운데',
    pagePosTopRight: '위 오른쪽',
    pageOrder: '페이지 순서',
    sidebarElements: '요소',
    sidebarBindings: '바인딩',
    typeBarcode: '바코드',
    expandRow: '펼치기',
    collapseRow: '접기',
    formSettings: '양식 설정',
    formTitle: '제목',
    paperSize: '용지 크기',
    paperCustom: '직접 입력',
    orientation: '방향',
    portrait: '세로',
    landscape: '가로',
    margin: '여백',
    marginTop: '위',
    marginRight: '오른쪽',
    marginBottom: '아래',
    marginLeft: '왼쪽',
    name: '이름',
    anchor: '기준점',
    anchorTL: '좌상',
    anchorT: '상',
    anchorTR: '우상',
    anchorL: '좌',
    anchorC: '중앙',
    anchorR: '우',
    anchorBL: '좌하',
    anchorB: '하',
    anchorBR: '우하',
    width: '너비',
    height: '높이',
    content: '내용',
    binding: '바인딩',
    formula: '수식',
    fontSize: '글자 크기',
    alignment: '정렬',
    rows: '행',
    columns: '열',
    cell: '선택 셀',
    cellHint: '선택된 표를 한 번 더 클릭하면 셀을 골라 바로 입력할 수 있습니다.',
    /** 그리드 (ADR-037) */
    rowHeight: '행 높이',
    columnWidth: '열 너비',
    overflow: '넘칠 때',
    overflowClip: '자르기',
    overflowShrink: '줄여 넣기',
    repeatSection: '반복 구간',
    repeatOn: '반복 사용',
    repeatFrom: '첫 행',
    repeatTo: '끝 행',
    repeatPerPage: '페이지당',
    repeatHeader: '헤더 반복',
    repeatCellHint: '반복',
    repeatFieldHint: '항목의 값 이름',
    cellSource: '칸 내용',
    cellSourceText: '고정 문구',
    cellSourceBinding: '값',
    cellSourceFormula: '수식',
    merge: '병합',
    columnKey: '데이터 키',
    src: '경로',
    backgroundColor: '배경색',
    fontColor: '글자색',
    borderColor: '테두리색',
    borderWidth: '테두리 굵기',
    colorNone: '없음',
    opacity: '투명도',
    hue: '색상',
    saveColor: '현재 색 저장',
    style: '스타일',
    previewLoading: 'PDF를 생성하고 있습니다…',
    previewError: 'PDF 생성에 실패했습니다.',
    pdfTitle: 'PDF 미리보기',
    typeText: '텍스트',
    typeGrid: '그리드',
    typeImage: '이미지',
    typeField: '입력 필드',
    alignLeft: '왼쪽',
    alignCenter: '가운데',
    alignRight: '오른쪽',
    shape: '도형',
    shapeRect: '사각형',
    shapeLine: '선',
    shapeEllipse: '타원',
    shapePolygon: '다각형',
    shapeTriangle: '삼각형',
    shapePentagon: '오각형',
    shapeHexagon: '육각형',
    sides: '변 수',
    bold: '굵게',
    underline: '밑줄',
    strikethrough: '취소선',
    verticalAlignment: '세로 정렬',
    alignTop: '위',
    alignMiddle: '가운데',
    alignBottom: '아래',
    lineHeight: '줄간격',
    characterSpacing: '자간',
    verticalWriting: '세로쓰기',
    styleText: '텍스트',
    styleBackground: '배경',
    styleBorder: '테두리',
    borderShape: '형태',
    /* 선은 테두리를 두르는 게 아니라 선 자체가 굵기·색·모양을 갖는다 (G-32) */
    /* 이미지 업로드 (G-36) — 업로드한 파일을 base64로 담는다. URL 입력은 두지 않는다 */
    imageModalTitle: '이미지 선택',
    imagePick: '이미지 업로드',
    imageReuse: '등록된 이미지',
    imageNone: '선택된 이미지 없음',
    imageSizeHint: '최대 {max}. 업로드한 이미지는 양식 파일에 포함됩니다',
    imageEmptyReuse: '등록된 이미지가 없습니다',
    imageChange: '이미지 변경',
    imageTooLarge: '이미지 용량 초과 — 최대 {max} (선택한 파일 {size})',
    imageNotImage: '이미지 파일이 아닙니다',
    imageReadFailed: '파일을 읽을 수 없습니다',
    /* 변동 이미지 (G-47) — 이미지 요소를 고정(src) 또는 변동(binding) 중 하나로 둔다 */
    imageMode: '이미지 방식',
    imageFixed: '고정 이미지',
    imageVariable: '변동 이미지',
    imageClear: '이미지 지우기',
    styleLine: '선',
    lineColor: '선 색',
    lineWidth: '선 굵기',
    lineShape: '선 모양',
    length: '길이',
    borderSolid: '실선',
    borderDashed: '파선',
    borderDotted: '점선',
    cornerRadius: '모서리 반경',
    formulaModalTitle: '수식 편집',
    apply: '적용',
    cancel: '취소',
    close: '닫기',
    formulaFunctions: '함수',
    formulaBindings: '바인딩 값',
    formulaQuoteHint: '문자열은 큰따옴표로 감쌉니다. 문자열 안에 큰따옴표를 넣으려면 ""처럼 두 번 씁니다.',
    formulaColumnSuggest: '열 고르기',
    syntaxError: '문법 오류',
    previewResult: '미리 계산',
    previewUnavailable: '계산 불가',
    orderForward: '앞으로',
    orderBackward: '뒤로',
    sampleData: '샘플 데이터',
    sampleModalTitle: '샘플 데이터 편집',
    sampleHint: '샘플 값을 채우면 미리보기가 그 값으로 채워진 전표를 보여줍니다.',
    addBinding: '바인딩 등록',
    bindingKey: '물리명',
    bindingLabel: '논리명',
    newBindingName: '값',
    bindingUsage: '쓰는 곳',
    bindingUnused: '아직 쓰는 요소가 없습니다.',
    bindingNew: '새 값 등록',
    columnPanelTitle: '표 열',
    keyInUse: '이미 쓰는 물리명입니다',
    evenWidths: '너비 균등하게',
    addRow: '행 추가',
    confirm: '확인',
    myForms: '내 양식',
    saveAsMyForm: '내 양식으로 저장',
    myFormsList: '내 양식 목록',
    save: '저장',
    saveAsNew: '새 양식으로 저장',
    search: '검색',
    loadMore: '더 보기',
    noSavedForms: '저장된 양식이 없습니다.',
    savedNotice: '내 양식에 저장했습니다.',
    formMode: '입력폼',
    jsonHint: '바인딩 이름을 키로 하는 JSON을 그대로 붙여 넣어 시험할 수 있습니다.',
    jsonInvalid: '올바른 JSON이 아닙니다',
    jsonNotObject: '맨 바깥은 객체({ }) 형태여야 합니다',
    lineDirection: '선 방향',
    lineHorizontal: '가로',
    lineVertical: '세로',
    lineDown: '사선 ↘',
    lineUp: '사선 ↗',
  },
  form: {
    noFile: '전표를 작성할 양식을 불러오세요.',
    parseError: '.slip 파일을 읽을 수 없습니다.',
    title: '전표 작성',
    noInputs: '이 양식에는 입력할 값이 없습니다.',
    computed: '자동 계산',
    calcError: '계산 오류',
    addRow: '행 추가',
    deleteRow: '행 삭제',
    issue: '발행',
    issued: '발행됨',
    issuedNotice: '발행된 전표는 더 이상 고칠 수 없습니다.',
    issueError: '발행하지 못했습니다.',
    reset: '입력 지우기',
    previewLoading: 'PDF를 생성하고 있습니다…',
    previewError: 'PDF 생성에 실패했습니다.',
    pdfTitle: 'PDF 미리보기',
    /* 변동 이미지 입력 (G-47) */
    imageUpload: '이미지 선택',
    imageClear: '이미지 지우기',
    imageNone: '선택된 이미지 없음',
    imageTooLarge: '이미지 용량 초과 — 최대 {max} (선택한 파일 {size})',
    imageNotImage: '이미지 파일이 아닙니다',
    imageReadFailed: '파일을 읽을 수 없습니다',
  },
  storage: {
    ioError: '저장소 작업에 실패했습니다.',
    notFound: '저장된 파일이 없습니다',
    badCursor: '잘못된 목록 커서입니다',
    noFileSelected: '선택된 파일이 없습니다.',
    pickCancelled: '파일 선택이 취소되었습니다.',
    deleteUnsupported: '로컬 파일 저장소는 삭제를 지원하지 않습니다.',
    listUnsupported: '로컬 파일 저장소는 목록 조회를 지원하지 않습니다.',
  },
};

/** 문구 사전의 형태 — 두 언어가 같은 키를 갖도록 컴파일 단계에서 강제한다 */
export type SlipStrings = typeof ko;

const en: SlipStrings = {
  viewer: {
    noFile: 'No .slip file to display.',
    loading: 'Generating PDF…',
    parseError: 'Could not read the .slip file.',
    renderError: 'PDF rendering failed.',
    pdfTitle: 'PDF preview',
  },
  designer: {
    noTemplate: 'Load a template to start.',
    parseError: 'Could not read the .slip file.',
    onlyTemplate: 'The designer can only edit template files.',
    addText: 'Text',
    addGrid: 'Grid',
    addImage: 'Image',
    addField: 'Field',
    delete: 'Delete',
    copy: 'Copy',
    paste: 'Paste',
    undo: 'Undo',
    redo: 'Redo',
    preview: 'Preview',
    edit: 'Edit',
    preset: 'Presets',
    presetTradeStatement: 'Transaction statement',
    presetInvoice: 'Invoice',
    addPage: 'Add page',
    deletePage: 'Delete page',
    showBadges: 'Show types',
    grid: 'Grid',
    gridNone: 'No grid',
    gridGap: 'Grid size',
    gridColor: 'Grid color',
    colorGray: 'Gray',
    colorBlue: 'Blue',
    colorRed: 'Red',
    colorGreen: 'Green',
    pageMoveForward: 'Move page forward',
    pageMoveBackward: 'Move page backward',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    sidebarPages: 'Pages',
    pageLabel: 'Page {n}',
    pageSettings: 'Page settings',
    pageName: 'Name',
    pageKey: 'Key',
    pageNameHint: 'Shown instead of the number in thumbnails and lists',
    pageNumberShow: 'Show page number',
    pageNumberPosition: 'Number position',
    pagePosBottomLeft: 'Bottom left',
    pagePosBottomCenter: 'Bottom center',
    pagePosBottomRight: 'Bottom right',
    pagePosTopLeft: 'Top left',
    pagePosTopCenter: 'Top center',
    pagePosTopRight: 'Top right',
    pageOrder: 'Page order',
    sidebarElements: 'Elements',
    sidebarBindings: 'Bindings',
    typeBarcode: 'Barcode',
    expandRow: 'Expand',
    collapseRow: 'Collapse',
    formSettings: 'Form settings',
    formTitle: 'Title',
    paperSize: 'Paper size',
    paperCustom: 'Custom',
    orientation: 'Orientation',
    portrait: 'Portrait',
    landscape: 'Landscape',
    margin: 'Margins',
    marginTop: 'Top',
    marginRight: 'Right',
    marginBottom: 'Bottom',
    marginLeft: 'Left',
    name: 'Name',
    anchor: 'Anchor',
    anchorTL: 'Top left',
    anchorT: 'Top',
    anchorTR: 'Top right',
    anchorL: 'Left',
    anchorC: 'Center',
    anchorR: 'Right',
    anchorBL: 'Bottom left',
    anchorB: 'Bottom',
    anchorBR: 'Bottom right',
    width: 'Width',
    height: 'Height',
    content: 'Content',
    binding: 'Binding',
    formula: 'Formula',
    fontSize: 'Font size',
    alignment: 'Align',
    rows: 'Rows',
    columns: 'Columns',
    cell: 'Selected cell',
    cellHint: 'Click the selected grid again to pick a cell and type.',
    /** Grid (ADR-037) */
    rowHeight: 'Row height',
    columnWidth: 'Column width',
    overflow: 'Overflow',
    overflowClip: 'Clip',
    overflowShrink: 'Shrink to fit',
    repeatSection: 'Repeating band',
    repeatOn: 'Repeat',
    repeatFrom: 'First row',
    repeatTo: 'Last row',
    repeatPerPage: 'Per page',
    repeatHeader: 'Header on next page',
    repeatCellHint: 'repeats',
    repeatFieldHint: 'field name of the item',
    cellSource: 'Cell content',
    cellSourceText: 'Fixed text',
    cellSourceBinding: 'Value',
    cellSourceFormula: 'Formula',
    merge: 'Merge',
    columnKey: 'Data key',
    src: 'Source',
    backgroundColor: 'Background',
    fontColor: 'Text color',
    borderColor: 'Border color',
    borderWidth: 'Border width',
    colorNone: 'None',
    opacity: 'Opacity',
    hue: 'Hue',
    saveColor: 'Save current color',
    style: 'Style',
    previewLoading: 'Generating PDF…',
    previewError: 'Failed to generate the PDF.',
    pdfTitle: 'PDF preview',
    typeText: 'Text',
    typeGrid: 'Grid',
    typeImage: 'Image',
    typeField: 'Input field',
    alignLeft: 'Left',
    alignCenter: 'Center',
    alignRight: 'Right',
    shape: 'Shape',
    shapeRect: 'Rectangle',
    shapeLine: 'Line',
    shapeEllipse: 'Ellipse',
    shapePolygon: 'Polygon',
    shapeTriangle: 'Triangle',
    shapePentagon: 'Pentagon',
    shapeHexagon: 'Hexagon',
    sides: 'Sides',
    bold: 'Bold',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    verticalAlignment: 'Vertical align',
    alignTop: 'Top',
    alignMiddle: 'Middle',
    alignBottom: 'Bottom',
    lineHeight: 'Line height',
    characterSpacing: 'Letter spacing',
    verticalWriting: 'Vertical text',
    styleText: 'Text',
    styleBackground: 'Background',
    styleBorder: 'Border',
    borderShape: 'Line style',
    imageModalTitle: 'Select image',
    imagePick: 'Upload image',
    imageReuse: 'Registered images',
    imageNone: 'No image selected',
    imageSizeHint: 'Up to {max}. Uploaded images are stored in the template file.',
    imageEmptyReuse: 'No registered images',
    imageChange: 'Change image',
    imageTooLarge: 'Image too large — max {max} (selected file is {size})',
    imageNotImage: 'Not an image file',
    imageReadFailed: 'Could not read the file',
    /* Variable image (G-47) — an image element is either fixed (src) or bound (binding) */
    imageMode: 'Image mode',
    imageFixed: 'Fixed image',
    imageVariable: 'Variable image',
    imageClear: 'Clear image',
    styleLine: 'Line',
    lineColor: 'Line color',
    lineWidth: 'Line width',
    lineShape: 'Line style',
    length: 'Length',
    borderSolid: 'Solid',
    borderDashed: 'Dashed',
    borderDotted: 'Dotted',
    cornerRadius: 'Corner radius',
    formulaModalTitle: 'Edit formula',
    apply: 'Apply',
    cancel: 'Cancel',
    close: 'Close',
    formulaFunctions: 'Functions',
    formulaBindings: 'Bindings',
    formulaQuoteHint: 'Wrap text in double quotes. To include a quote inside text, type it twice ("").',
    formulaColumnSuggest: 'Pick a column',
    syntaxError: 'Syntax error',
    previewResult: 'Preview',
    previewUnavailable: 'Cannot evaluate',
    orderForward: 'Move forward',
    orderBackward: 'Move backward',
    sampleData: 'Sample data',
    sampleModalTitle: 'Edit sample data',
    sampleHint: 'Fill in sample values and the preview shows a voucher filled with them.',
    addBinding: 'Add binding',
    bindingKey: 'Key',
    bindingLabel: 'Label',
    newBindingName: 'Value',
    bindingUsage: 'Used in',
    bindingUnused: 'Not used by any element yet.',
    bindingNew: 'Register new value',
    columnPanelTitle: 'Table column',
    keyInUse: 'That key is already in use',
    evenWidths: 'Equal widths',
    addRow: 'Add row',
    confirm: 'OK',
    myForms: 'My forms',
    saveAsMyForm: 'Save to my forms',
    myFormsList: 'My forms',
    save: 'Save',
    saveAsNew: 'Save as a new form',
    search: 'Search',
    loadMore: 'Load more',
    noSavedForms: 'No saved forms yet.',
    savedNotice: 'Saved to my forms.',
    formMode: 'Form',
    jsonHint: 'Paste JSON keyed by binding names to test it directly.',
    jsonInvalid: 'Not valid JSON',
    jsonNotObject: 'The top level must be an object ({ })',
    lineDirection: 'Line direction',
    lineHorizontal: 'Horizontal',
    lineVertical: 'Vertical',
    lineDown: 'Diagonal ↘',
    lineUp: 'Diagonal ↗',
  },
  form: {
    noFile: 'Load a template to fill in a slip.',
    parseError: 'Could not read the .slip file.',
    title: 'Fill in slip',
    noInputs: 'This template has no values to fill in.',
    computed: 'Calculated',
    calcError: 'Calculation error',
    addRow: 'Add row',
    deleteRow: 'Delete row',
    issue: 'Issue',
    issued: 'Issued',
    issuedNotice: 'An issued slip can no longer be edited.',
    issueError: 'Could not issue the slip.',
    reset: 'Clear values',
    previewLoading: 'Generating PDF…',
    previewError: 'Failed to generate the PDF.',
    pdfTitle: 'PDF preview',
    /* Variable image input (G-47) */
    imageUpload: 'Select image',
    imageClear: 'Clear image',
    imageNone: 'No image selected',
    imageTooLarge: 'Image too large — max {max} (selected file is {size})',
    imageNotImage: 'Not an image file',
    imageReadFailed: 'Could not read the file',
  },
  storage: {
    ioError: 'Storage operation failed.',
    notFound: 'No saved file',
    badCursor: 'Invalid list cursor',
    noFileSelected: 'No file was selected.',
    pickCancelled: 'File selection was cancelled.',
    deleteUnsupported: 'Local file storage does not support delete.',
    listUnsupported: 'Local file storage does not support listing.',
  },
};

/** 언어별 문구 사전 전체 */
export const STRINGS: Record<SlipLocale, SlipStrings> = { ko, en };

/**
 * 로케일에 맞는 문구 사전을 돌려준다. 'en-US'처럼 지역이 붙어도 언어만 보고
 * 고르며, 모르는 로케일은 한국어(기본)로 돌아간다.
 *
 * @param locale - UI 언어 (생략하면 한국어)
 * @returns 해당 언어의 문구 사전
 */
export function getStrings(locale?: string): SlipStrings {
  const language = locale?.toLowerCase().split('-')[0];
  return language && language in STRINGS ? STRINGS[language as SlipLocale] : STRINGS.ko;
}

/** 한국어 사전 — 프리셋 등 한국어 고정 데이터와 기존 코드가 참조한다 */
export const strings = ko;
